#+chunk-id: org-guide-chunk-0001
#+source-file: org-guide
#+heading-path: Preamble
#+start-line: 1
#+end-line: 738
#+external-urls: http://www.astro.uva.nl/=dominik=
#+mirrored-urls: 
#+title: Org Mode Compact Guide
#+subtitle:  Release {{{version}}}
#+author: The Org Mode Developers
#+language: en

#+texinfo: @insertcopying

* Copying
:PROPERTIES:
:copying:  t
:END:

Copyright \copy 2004--2026  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being "A GNU Manual,"
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled "GNU Free Documentation License."
in the full Org manual, which is distributed together with this
compact guide.

(a) The FSF's Back-Cover Text is: "You have the freedom to copy and
modify this GNU manual."
#+end_quote

* Introduction
:PROPERTIES:
:DESCRIPTION: Welcome!
:END:

Org is a mode for keeping notes, maintaining TODO lists, and doing
project planning with a fast and effective plain-text system.  It is
also an authoring and publishing system, and it supports working with
source code for literate programming and reproducible research.

This document is a much compressed derivative of the [[info:org][comprehensive Org
mode manual]].  It contains all basic features and commands, along with
important hints for customization.  It is intended for beginners who
would shy back from a 200 pages manual because of sheer size.

** Installation
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+attr_texinfo: :tag Important
#+begin_quote
If you are using a version of Org that is part of the Emacs
distribution, please skip this section and go directly to [[*Activation]].
#+end_quote

If you have downloaded Org from the web, either as a distribution
=.zip= or =.tar= file, or as a Git archive, it is best to run it
directly from the distribution directory.  You need to add the =lisp/=
subdirectories to the Emacs load path.  To do this, add the following
line to your Emacs init file:

: (add-to-list 'load-path "~/path/to/orgdir/lisp")

#+texinfo: @noindent
If you have been using git or a tar ball to get Org, you need to run
the following command to generate autoload information.

: make autoloads

** Activation
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Add the following lines to your Emacs init file to define /global/
keys for three commands that are useful in any Emacs buffer, not just
Org buffers.  Please choose suitable keys yourself.

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)
#+end_src

Files with extension =.org= will be put into Org mode automatically.

** Feedback
:PROPERTIES:
:UNNUMBERED: notoc
:END:

If you find problems with Org, or if you have questions, remarks, or
ideas about it, please mail to the Org mailing list
mailto:emacs-orgmode@gnu.org.  For information on how to submit bug
reports, see the [[info:org][main manual]].

* Document Structure
:PROPERTIES:
:DESCRIPTION: A tree works like your brain.
:END:

Org is an outliner.  Outlines allow a document to be organized in
a hierarchical structure, which, at least for me, is the best
representation of notes and thoughts.  An overview of this structure
is achieved by folding, i.e., hiding large parts of the document to
show only the general document structure and the parts currently being
worked on.  Org greatly simplifies the use of outlines by compressing
the entire show and hide functionalities into a single command,
~org-cycle~, which is bound to the {{{kbd(TAB)}}} key.

** Headlines
:PROPERTIES:
:DESCRIPTION: How to typeset Org tree nodes.
:END:

Headlines define the structure of an outline tree.  The headlines in
Org start on the left margin[fn:1] with one or more stars followed by
a space.  For example:

#+begin_example
,* First (top) level headline
,** Second level
,*** Third level
    some text
,*** Third level
    more text
,* Another first (top) level headline
#+end_example

Note that a headline named after ~org-footnote-section~, which
defaults to =Footnotes=, is considered as special.  A subtree with
this headline will be silently ignored by exporting functions.

Some people find the many stars too noisy and would prefer an outline
that has whitespace followed by a single star as headline starters.
See [[*Miscellaneous]] for a setup to realize this.

** Visibility Cycling
:PROPERTIES:
:DESCRIPTION: Show and hide, much simplified.
:END:

Outlines make it possible to hide parts of the text in the buffer.
Org uses just two commands, bound to {{{kbd(TAB)}}} and
{{{kbd(S-TAB)}}} (~org-cycle~ and ~org-shifttab~) to change the
visibility in the buffer.

#+attr_texinfo: :sep ,
- {{{kbd(TAB)}}} (~org-cycle~) ::

  /Subtree cycling/: Rotate current subtree among the states

 : ,-> FOLDED -> CHILDREN -> SUBTREE --.
 : '-----------------------------------'

  When called with a prefix argument ({{{kbd(C-u TAB)}}}), or with the
  Shift key, global cycling is invoked.

- {{{kbd(S-TAB)}}} (~org-global-cycle~), {{{kbd(C-u TAB)}}} (~org-cycle~) ::

  /Global cycling/: Rotate the entire buffer among the states

  : ,-> OVERVIEW -> CONTENTS -> SHOW ALL --.
  : '--------------------------------------'

- {{{kbd(C-u C-u C-u TAB)}}} (~org-fold-show-all~) ::

  Show all, including drawers.

When Emacs first visits an Org file, the global state is set to
~showeverything~, i.e., all file content is visible.  This can be
configured through the variable ~org-startup-folded~, or on a per-file
basis by adding a =STARTUP= keyword to =overview=, =content=,
=showall=, =showeverything= or =show<n>levels= (n = 2..5) like this:

: #+STARTUP: content

** Motion
:PROPERTIES:
:DESCRIPTION: Jumping to other headlines.
:END:

The following commands jump to other headlines in the buffer.

- {{{kbd(C-c C-n)}}} (~org-next-visible-heading~) :: Next heading.
- {{{kbd(C-c C-p)}}} (~org-previous-visible-heading~) :: Previous
  heading.

- {{{kbd(C-c C-f)}}} (~org-backward-heading-same-level~) :: Next
  heading same level.

- {{{kbd(C-c C-b)}}} (~outline-backward-same-level~) :: Previous
  heading same level.

- {{{kbd(C-c C-u)}}} (~outline-up-heading~) :: Backward to higher
  level heading.

** Structure Editing
:PROPERTIES:
:DESCRIPTION: Changing sequence and level of headlines.
:END:

#+attr_texinfo: :sep ,
- {{{kbd(M-RET)}}} (~org-meta-return~) ::

  Insert new heading with same level as current.  If point is in
  a plain list item, a new item is created (see [[Plain Lists]]).  When
  this command is used in the middle of a line, the line is split and
  the rest of the line becomes the new headline[fn:2].

- {{{kbd(M-S-RET)}}} (~org-insert-todo-heading~) ::

  Insert new TODO entry with same level as current heading.

- {{{kbd(TAB)}}} (~org-cycle~) in new, empty entry ::

  In a new entry with no text yet, {{{kbd(TAB)}}} cycles through
  reasonable levels.

- {{{kbd(M-LEFT)}}} (~org-metaleft~), {{{kbd(M-RIGHT)}}} (~org-metaright~) ::

  Promote or demote current heading by one level.

- {{{kbd(M-UP)}}} (~org-move-subtree-up~), {{{kbd(M-DOWN)}}} (~org-move-subtree-down~) ::

  Move subtree up or down, i.e., swap with previous or next subtree of
  same level.

- {{{kbd(C-c C-w)}}} (~org-refile~) ::

  Refile entry or region to a different location.  See [[*Refile and
  Copy]].

- {{{kbd(C-x n s)}}} (~org-narrow-to-subtree~), {{{kbd(C-x n w)}}} (~widen~) ::

  Narrow buffer to current subtree and widen it again.

When there is an active region (Transient Mark mode), promotion and
demotion work on all headlines in the region.

** Sparse Trees
:PROPERTIES:
:DESCRIPTION: Matches embedded in context.
:END:

An important feature of Org mode is the ability to construct /sparse
trees/ for selected information in an outline tree, so that the entire
document is folded as much as possible, but the selected information
is made visible along with the headline structure above it[fn:3].
Just try it out and you will see immediately how it works.

Org mode contains several commands creating such trees, all these
commands can be accessed through a dispatcher:

- {{{kbd(C-c /)}}} (~org-sparse-tree~) ::

  This prompts for an extra key to select a sparse-tree creating
  command.

- {{{kbd(C-c / r)}}} (~org-occur~) ::

  Occur.  Prompts for a regexp and shows a sparse tree with all
  matches.  Each match is also highlighted; the highlights disappear
  by pressing {{{kbd(C-c C-c)}}}.

  The other sparse tree commands select headings based on TODO
  keywords, tags, or properties and will be discussed later in this
  manual.

** Plain Lists
:PROPERTIES:
:DESCRIPTION: Additional structure within an entry.
:END:

Within an entry of the outline tree, hand-formatted lists can provide
additional structure.  They also provide a way to create lists of
checkboxes (see [[*Checkboxes]]).  Org supports editing such lists, and
every exporter (see [[*Exporting]]) can parse and format them.

Org knows ordered lists, unordered lists, and description lists.

#+attr_texinfo: :indic @bullet
- /Unordered/ list items start with =-=, =+=, or =*= as bullets.

- /Ordered/ list items start with =1.=, or =1)=.

- /Description/ list use =::= to separate the /term/ from the
  description.

Items belonging to the same list must have the same indentation on the
first line.  An item ends before the next line that is indented like
its bullet/number, or less.  A list ends when all items are closed, or
before two blank lines.  An example:

#+begin_example
,* Lord of the Rings
  My favorite scenes are (in this order)
  1. The attack of the Rohirrim
  2. Eowyn's fight with the witch king
     + this was already my favorite scene in the book
     + I really like Miranda Otto.
  Important actors in this film are:
  - Elijah Wood :: He plays Frodo
  - Sean Astin :: He plays Sam, Frodo's friend.
#+end_example

The following commands act on items when point is in the first line of
an item (the line with the bullet or number).

#+attr_texinfo: :sep ,
- {{{kbd(TAB)}}} (~org-cycle~) ::

  Items can be folded just like headline levels.

- {{{kbd(M-RET)}}} (~org-insert-heading~) ::

  Insert new item at current level.  With a prefix argument, force
  a new heading (see [[*Structure Editing]]).

- {{{kbd(M-S-RET)}}} (~org-insert-todo-heading~) ::

  Insert a new item with a checkbox (see [[*Checkboxes]]).

- {{{kbd(M-UP)}}} (~org-move-item-up~), {{{kbd(M-DOWN)}}} (~org-move-item-down~) ::

  Move the item including subitems up/down (swap with previous/next
  item of same indentation).  If the list is ordered, renumbering is
  automatic.

- {{{kbd(M-LEFT)}}} (~org-do-promote~), {{{kbd(M-RIGHT)}}} (~org-do-demote~) ::

  Decrease/increase the indentation of an item, leaving children
  alone.

- {{{kbd(M-S-LEFT)}}} (~org-promote-subtree~), {{{kbd(M-S-RIGHT)}}} (~org-demote-subtree~) ::

  Decrease/increase the indentation of the item, including subitems.

- {{{kbd(C-c C-c)}}} (~org-toggle-checkbox~) ::

  If there is a checkbox (see [[*Checkboxes]]) in the item line, toggle
  the state of the checkbox.  Also verify bullets and indentation
  consistency in the whole list.

- {{{kbd(C-c -)}}} (~org-cycle-list-bullet~) ::

  Cycle the entire list level through the different itemize/enumerate
  bullets (=-=, =+=, =*=, =1.=, =1)=).

* Tables
:PROPERTIES:
:DESCRIPTION: Pure magic for quick formatting.
:END:

Org comes with a fast and intuitive table editor.  Spreadsheet-like
calculations are supported in connection with the Emacs Calc package
(see [[info:calc][GNU Emacs Calculator Manual]]).

Org makes it easy to format tables in plain ASCII.  Any line with =|=
as the first non-whitespace character is considered part of a table.
=|= is also the column separator.  A table might look like this:

#+begin_example
| Name  | Phone | Age |
|-------+-------+-----|
| Peter |  1234 |  17 |
| Anna  |  4321 |  25 |
#+end_example

A table is re-aligned automatically each time you press {{{kbd(TAB)}}}
or {{{kbd(RET)}}} or {{{kbd(C-c C-c)}}} inside the table.
{{{kbd(TAB)}}} also moves to the next field ({{{kbd(RET)}}} to the
next row) and creates new table rows at the end of the table or before
horizontal lines.  The indentation of the table is set by the first
line.  Any line starting with =|-= is considered as a horizontal
separator line and will be expanded on the next re-align to span the
whole table width.  So, to create the above table, you would only type

: |Name|Phone|Age|
: |-

#+texinfo: @noindent
and then press {{{kbd(TAB)}}} to align the table and start filling in
fields.  Even faster would be to type =|Name|Phone|Age= followed by
{{{kbd(C-c RET)}}}.

When typing text into a field, Org treats {{{kbd(DEL)}}},
{{{kbd(Backspace)}}}, and all character keys in a special way, so that
inserting and deleting avoids shifting other fields.  Also, when
typing /immediately after point was moved into a new field with
{{{kbd(TAB)}}}, {{{kbd(S-TAB)}}} or {{{kbd(RET)}}}/, the field is
automatically made blank.

** Creation and conversion
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- {{{kbd(C-c |)}}} (~org-table-create-or-convert-from-region~) ::

  Convert the active region to table.  If every line contains at least
  one {{{kbd(TAB)}}} character, the function assumes that the material
  is tab separated.  If every line contains a comma, comma-separated
  values (CSV) are assumed.  If not, lines are split at whitespace
  into fields.

  If there is no active region, this command creates an empty Org
  table.  But it is easier just to start typing, like {{{kbd(|
  N a m e | P h o n e | A g e RET | - TAB)}}}.

** Re-aligning and field motion
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+attr_texinfo: :sep ,
- {{{kbd(C-c C-c)}}} (~org-table-align~) ::

  Re-align the table without moving point.

- {{{kbd(TAB)}}} (~org-table-next-field~) ::

  Re-align the table, move to the next field.  Creates a new row if
  necessary.

- {{{kbd(S-TAB)}}} (~org-table-previous-field~) ::

  Re-align, move to previous field.

- {{{kbd(RET)}}} (~org-table-next-row~) ::

  Re-align the table and move down to next row.  Creates a new row if
  necessary.

- {{{kbd(S-UP)}}} (~org-table-move-cell-up~), {{{kbd(S-DOWN)}}} (~org-table-move-cell-down~), {{{kbd(S-LEFT)}}} (~org-table-move-cell-left~), {{{kbd(S-RIGHT)}}} (~org-table-move-cell-right~) ::

  Move a cell up, down, left, and right by swapping with adjacent
  cell.

** Column and row editing
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- {{{kbd(M-LEFT)}}} (~org-table-move-column-left~), {{{kbd(M-RIGHT)}}} (~org-table-move-column-right~) ::

  Move the current column left/right.

- {{{kbd(M-S-LEFT)}}} (~org-table-delete-column~) ::

  Kill the current column.

- {{{kbd(M-S-RIGHT)}}} (~org-table-insert-column~) ::

  Insert a new column to the left of point position.

- {{{kbd(M-UP)}}} (~org-table-move-row-up~), {{{kbd(M-DOWN)}}} (~org-table-move-row-down~) ::

  Move the current row up/down.

- {{{kbd(M-S-UP)}}} (~org-table-kill-row~) ::

  Kill the current row or horizontal line.

- {{{kbd(M-S-DOWN)}}} (~org-table-insert-row~) ::

  Insert a new row above the current row.  With a prefix argument, the
  line is created below the current one.

- {{{kbd(C-c -)}}} (~org-table-insert-hline~) ::

  Insert a horizontal line below current row.  With a prefix argument,
  the line is created above the current line.

- {{{kbd(C-c RET)}}} (~org-table-hline-and-move~) ::

  Insert a horizontal line below current row, and move the point into
  the row below that line.

- {{{kbd(C-c ^)}}} (~org-table-sort-lines~) ::

  Sort the table lines in the region.  The position of point indicates
  the column to be used for sorting, and the range of lines is the
  range between the nearest horizontal separator lines, or the entire
  table.

* Hyperlinks
:PROPERTIES:
:DESCRIPTION: Notes in context.
:END:

Like HTML, Org provides links inside a file, external links to other
files, Usenet articles, emails, and much more.

Org recognizes plain URIs, possibly wrapped within angle brackets, and
activate them as clickable links.  The general link format, however,
looks like this:

: [[LINK][DESCRIPTION]]

#+texinfo: @noindent
or alternatively

: [[LINK]]

Once a link in the buffer is complete, with all brackets present, Org
changes the display so that =DESCRIPTION= is displayed instead of
=[[LINK][DESCRIPTION]]= and =LINK= is displayed instead of =[[LINK]]=.
To edit the invisible {{{var(LINK)}}} part, use {{{kbd(C-c C-l)}}}
with the point on the link.

** Internal links
:PROPERTIES:
:UNNUMBERED: notoc
:END:

If the link does not look like a URL, it is considered to be internal
in the current file.  The most important case is a link like
=[[#my-custom-id]]= which links to the entry with the =CUSTOM_ID= property
=my-custom-id=.

Links such as =[[My Target]]= or =[[My Target][Find my target]]= lead
to a text search in the current file for the corresponding target,
which looks like =<<My Target>>=.

** External Links
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Org supports links to files, websites, Usenet and email messages, BBDB
database entries and links to both IRC conversations and their logs.
External links are URL-like locators.  They start with a short
identifying string followed by a colon.  There can be no space after
the colon.  Here are some examples:

| =http://www.astro.uva.nl/=dominik=        | on the web                                  |
| =file:/home/dominik/images/jupiter.jpg=   | file, absolute path                         |
| =/home/dominik/images/jupiter.jpg=        | same as above                               |
| =file:papers/last.pdf=                    | file, relative path                         |
| =./papers/last.pdf=                       | same as above                               |
| =file:projects.org=                       | another Org file                            |
| =docview:papers/last.pdf::NNN=            | open in DocView mode at page {{{var(NNN)}}} |
| =id:B7423F4D-2E8A-471B-8810-C40F074717E9= | link to heading by ID                       |
| =news:comp.emacs=                         | Usenet link                                 |
| =mailto:adent@galaxy.net=                 | mail link                                   |
| =mhe:folder#id=                           | MH-E message link                           |
| =rmail:folder#id=                         | Rmail message link                          |
| =gnus:group#id=                           | Gnus article link                           |
| =bbdb:R.*Stallman=                        | BBDB link (with regexp)                     |
| =irc:/irc.com/#emacs/bob=                 | IRC link                                    |
| =info:org#Hyperlinks=                     | Info node link                              |

File links can contain additional information to make Emacs jump to
a particular location in the file when following a link. This can be
a line number or a search option after a double colon. Here are a few
examples, together with an explanation:

| =file:~/code/main.c::255=          | Find line 255               |
| =file:~/xx.org::My Target=         | Find =<<My Target>>=        |
| =[[file:~/xx.org::#my-custom-id]]= | Find entry with a custom ID |

** Handling Links
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Org provides methods to create a link in the correct syntax, to insert
it into an Org file, and to follow the link.

The main function is ~org-store-link~, called with {{{kbd(M-x
org-store-link)}}}.  Because of its importance, we suggest to bind it
to a widely available key (see [[*Activation]]).  It stores a link to the
current location.  The link is stored for later insertion into an Org
buffer---see below.

From an Org buffer, the following commands create, navigate or, more
generally, act on links.

#+attr_texinfo: :sep ,
- {{{kbd(C-c C-l)}}} (~org-insert-link~) ::

  Insert a link.  This prompts for a link to be inserted into the
  buffer.  You can just type a link, or use history keys {{{kbd(UP)}}}
  and {{{kbd(DOWN)}}} to access stored links.  You will be prompted
  for the description part of the link.

  When called with a {{{kbd(C-u)}}} prefix argument, file name
  completion is used to link to a file.

- {{{kbd(C-c C-l)}}} (with point on existing link) (~org-insert-link~) ::

  When point is on an existing link, {{{kbd(C-c C-l)}}} allows you to
  edit the link and description parts of the link.

- {{{kbd(C-c C-o)}}} (~open-link-at-point~) ::

  Open link at point.

- {{{kbd(C-c &)}}} (~org-mark-ring-goto~) ::

  Jump back to a recorded position.  A position is recorded by the
  commands following internal links, and by {{{kbd(C-c %)}}}.  Using
  this command several times in direct succession moves through a ring
  of previously recorded positions.

* TODO Items
:PROPERTIES:
:DESCRIPTION: Every tree branch can be a TODO item.
:END:

Org mode does not require TODO lists to live in separate documents.
Instead, TODO items are part of a notes file, because TODO items
usually come up while taking notes!  With Org mode, simply mark any
entry in a tree as being a TODO item.  In this way, information is not
duplicated, and TODO items remain in the context from which they
emerged.

Org mode provides methods to give you an overview of all the things
that you have to do, collected from many files.

** Basic TODO Functionality
:PROPERTIES:
:DESCRIPTION: Marking and displaying TODO entries.
:ALT_TITLE: TODO Basics
:END:

Any headline becomes a TODO item when it starts with the word =TODO=,
for example:

: *** TODO Write letter to Sam Fortune

The most important commands to work with TODO entries are:

#+attr_texinfo: :sep ,
- {{{kbd(C-c C-t)}}} (~org-todo~) ::

  Rotate the TODO state of the current item among

  : ,-> (unmarked) -> TODO -> DONE --.
  : '--------------------------------'

  The same rotation can also be done "remotely" from the agenda buffer
  with the {{{kbd(t)}}} command key (see [[*Commands in the Agenda
  Buffer]]).

- {{{kbd(S-RIGHT)}}} (~org-shiftright~), {{{kbd(S-LEFT)}}} (~org-shiftleft~) ::

  Select the following/preceding TODO state, similar to cycling.

- {{{kbd(C-c / t)}}} (~org-show-todo-tree~) ::

  View TODO items in a /sparse tree/ (see [[*Sparse Trees]]).  Folds the
  entire buffer, but shows all TODO items---with not-DONE state---and
  the headings hierarchy above them.

- {{{kbd(M-x org-agenda t)}}} (~org-todo-list~) ::

  Show the global TODO list.  Collects the TODO items (with not-DONE
  states) from all agenda files (see [[*Agenda Views]]) into a single
  buffer.  See [[*The Global TODO List]], for more information.

- {{{kbd(S-M-RET)}}} (~org-insert-todo-heading~) ::

  Insert a new TODO entry below the current one.

Changing a TODO state can also trigger tag changes.  See the docstring
of the option ~org-todo-state-tags-triggers~ for details.

** Multi-state Workflow
:PROPERTIES:
:DESCRIPTION: More than just on/off.
:END:

You can use TODO keywords to indicate /sequential/ working progress
states:

#+begin_src emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO" "FEEDBACK" "VERIFY" "|" "DONE" "DELEGATED")))
#+end_src

#+texinfo: @noindent
The vertical bar separates the =TODO= keywords (states that /need
action/) from the =DONE= states (which need /no further action/).  If
you do not provide the separator bar, the last state is used as the
=DONE= state.  With this setup, the command {{{kbd(C-c C-t)}}} cycles
an entry from =TODO= to =FEEDBACK=, then to =VERIFY=, and finally to
=DONE= and =DELEGATED=.

Sometimes you may want to use different sets of TODO keywords in
parallel.  For example, you may want to have the basic =TODO=/=DONE=,
but also a workflow for bug fixing.  Your setup would then look like
this:

#+begin_src emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO(t)" "|" "DONE(d)")
        (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f)")))
#+end_src

#+texinfo: @noindent
The keywords should all be different, this helps Org mode to keep
track of which subsequence should be used for a given entry.  The
example also shows how to define keys for fast access of a particular
state, by adding a letter in parenthesis after each keyword---you will
be prompted for the key after {{{kbd(C-c C-t)}}}.

To define TODO keywords that are valid only in a single file, use the
following text anywhere in the file.

#+begin_example
,#+TODO: TODO(t) | DONE(d)
,#+TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
,#+TODO: | CANCELED(c)
#+end_example

After changing one of these lines, use {{{kbd(C-c C-c)}}} with the
cursor still in the line to make the changes known to Org mode.

** Progress Logging
:PROPERTIES:
:DESCRIPTION: Dates and notes for progress.
:END:

To record a timestamp and a note when changing a TODO state, call the
command ~org-todo~ with a prefix argument.

#+attr_texinfo: :sep ,
- {{{kbd(C-u C-c C-t)}}} (~org-todo~) ::
  Prompt for a note and record the time of the TODO state change.

Org mode can also automatically record a timestamp and optionally a
note when you mark a TODO item as DONE, or even each time you change
the state of a TODO item.  This system is highly configurable,
settings can be on a per-keyword basis and can be localized to a file
or even a subtree.  For information on how to clock working time for a
task, see [[*Clocking Work Time]].

