#+chunk-id: org-manual-chunk-0036
#+source-file: org-manual
#+heading-path: TODO Items > Extended Use of TODO Keywords > TODO dependencies
#+start-line: 4270
#+end-line: 4350
#+external-urls: 
#+mirrored-urls: 
*** TODO dependencies
:PROPERTIES:
:DESCRIPTION: When one task needs to wait for others.
:END:
#+cindex: TODO dependencies
#+cindex: dependencies, of TODO states

#+vindex: org-enforce-todo-dependencies
#+cindex: @samp{ORDERED}, property
The structure of Org files---hierarchy and lists---makes it easy to
define TODO dependencies.  Usually, a parent TODO task should not be
marked as done until all TODO subtasks, or children tasks, are marked
as done.  Sometimes there is a logical sequence to (sub)tasks, so that
one subtask cannot be acted upon before all siblings above it have
been marked as done.  If you customize the variable
~org-enforce-todo-dependencies~, Org blocks entries from changing
state to DONE while they have TODO children that are not DONE.
Furthermore, if an entry has a property =ORDERED=, each of its TODO
children is blocked until all earlier siblings are marked as done.
Here is an example:

#+begin_example
,* TODO Blocked until (two) is done
,** DONE one
,** TODO two

,* Parent
:PROPERTIES:
:ORDERED:  t
:END:
,** TODO a
,** TODO b, needs to wait for (a)
,** TODO c, needs to wait for (a) and (b)
#+end_example

#+cindex: TODO dependencies, @samp{NOBLOCKING}
#+cindex: @samp{NOBLOCKING}, property
You can ensure an entry is never blocked by using the =NOBLOCKING=
property (see [[*Properties and Columns]]):

#+begin_example
,* This entry is never blocked
:PROPERTIES:
:NOBLOCKING: t
:END:
#+end_example

- {{{kbd(C-c C-x o)}}} (~org-toggle-ordered-property~) ::

  #+kindex: C-c C-x o
  #+findex: org-toggle-ordered-property
  #+vindex: org-track-ordered-property-with-tag
  Toggle the =ORDERED= property of the current entry.  A property is
  used for this behavior because this should be local to the current
  entry, not inherited from entries above like a tag (see [[*Tags]]).
  However, if you would like to /track/ the value of this property
  with a tag for better visibility, customize the variable
  ~org-track-ordered-property-with-tag~.

- {{{kbd(C-u C-u C-u C-c C-t)}}} ::

  #+kindex: C-u C-u C-u C-u C-c C-t
  Change TODO state, regardless of any state blocking.

#+vindex: org-agenda-dim-blocked-tasks
If you set the variable ~org-agenda-dim-blocked-tasks~, TODO entries
that cannot be marked as done because of unmarked children are shown
in a dimmed font or even made invisible in agenda views (see [[*Agenda
Views]]).

#+cindex: checkboxes and TODO dependencies
#+vindex: org-enforce-todo-dependencies
You can also block changes of TODO states by using checkboxes (see
[[*Checkboxes]]).  If you set the variable
~org-enforce-todo-checkbox-dependencies~, an entry that has unchecked
checkboxes is blocked from switching to DONE.

If you need more complex dependency structures, for example
dependencies between entries in different trees or files, check out
the module =org-depend.el= in the =org-contrib= repository.

