#+chunk-id: org-manual-chunk-0001
#+source-file: org-manual
#+heading-path: Preamble
#+start-line: 1
#+end-line: 107
#+external-urls: https://orgmode.org
#+mirrored-urls: https://orgmode.org
#+title: The Org Manual
#+subtitle:  Release {{{version}}}
#+author:    The Org Mode Developers
#+language:  en
#+startup: literallinks


#+texinfo: @insertcopying

* Introduction
:PROPERTIES:
:DESCRIPTION: Getting started.
:END:
#+cindex: introduction

** Summary
:PROPERTIES:
:DESCRIPTION: Brief summary of what Org does.
:END:
#+cindex: summary

Org mode is an authoring tool and a TODO list manager for GNU Emacs.
It relies on a lightweight plain-text markup language used in files
with the =.org= extension.

Authoring Org files is best supported by Emacs, but you can view,
understand, and change them with any text editor.

As an authoring tool, Org helps you write structured documents and
provides exporting facilities.  Org files can also be used for literate
programming and reproducible research.  As a TODO list manager, Org
helps you organize your tasks in a flexible way, from daily needs to
detailed project planning, allowing logging, multiple views of your
tasks, exporting your agendas, etc.

Org mode is implemented on top of Outline mode, which makes it
possible to keep the content of large files well-structured.
Visibility cycling and structure editing help you work with the tree.
Tables are easily created with a built-in table editor.  Plain text
URL-like links connect to websites, emails, Usenet messages, BBDB
entries, and any files related to the projects.

Org develops organizational tasks around note files that contain
lists or information about projects as plain text.  Project planning
and task management make use of metadata, which is part of an outline
node.  Based on this data, specific entries can be extracted via
queries to create dynamic /agenda views/ that also integrate the Emacs
calendar and diary.  Org can be used to implement many different
project planning schemes, such as David Allen's GTD system.

Org files can serve as a single-source authoring system with export to
many different formats such as HTML, LaTeX, Open Document, and
Markdown.  New export backends can be derived from existing ones, or
defined from scratch.

Org files can include source code blocks, which makes Org uniquely
suited for authoring technical documents with code examples.  Org
source code blocks are fully functional; they can be evaluated in
place and their results can be captured in the file.  This makes it
possible to create a single-file reproducible research compendium.

Org keeps simple things simple.  When first fired up, it should feel
like a straightforward, easy-to-use outliner.  Complexity is not
imposed, but a large amount of functionality is available when needed.
Org is a toolbox.  Many users actually run only a---very
personal---fraction of Org's capabilities, and know that there is more
whenever they need it.

All of this is achieved with strictly plain text files, the most
portable and future-proof file format.  Org runs in Emacs.  Emacs is
one of the most widely ported programs, so that Org mode is available
on every major platform.

#+cindex: FAQ
There is a website for Org which provides links to the newest version
of Org, as well as additional information, frequently asked questions
(FAQ), links to tutorials, etc.  This page is located at
[[../../mirror/by-url/8f1099ddb6d95a5a3d22e4d5fb5cf198457425bd218d3581a8c4a02e753cefd1.html]].

#+cindex: print edition
An earlier version (7.3) of this manual was available as a paperback
book from the Network Theory Ltd. publishing company, which closed
in 2009.

** Installation
:PROPERTIES:
:DESCRIPTION: Installing Org.
:END:
#+cindex: installation

Org is included in distributions of GNU Emacs, so you probably do not
need to install it.  Most users will simply activate Org and begin
exploring its features.

If, for one reason or another, you want to install Org on top of the
pre-packaged version, you can use the Emacs package system or clone
Org's Git repository.  We *strongly recommend* sticking to a single
installation method.

When installing Org on top of the pre-packaged version, please note
that Org stable versions are meant to be fully compatible with the
last three stable versions of Emacs but not with older Emacsen.

Some Org components also depend on third-party packages available
through package archives.  Org is only guaranteed to be compatible
with the latest stable versions of these third-party packages.

