#+chunk-id: org-manual-chunk-0021
#+source-file: org-manual
#+heading-path: Tables > The Spreadsheet > Durations and time values
#+start-line: 2373
#+end-line: 2407
#+external-urls: 
#+mirrored-urls: 
*** Durations and time values
:PROPERTIES:
:DESCRIPTION: How to compute durations and time values.
:END:
#+cindex: duration, computing
#+cindex: time, computing
#+vindex: org-table-duration-custom-format

If you want to compute time values use the =T=, =t=, or =U= flag,
either in Calc formulas or Elisp formulas:

#+begin_example
|  Task 1 |   Task 2 |    Total |
|---------+----------+----------|
|    2:12 |     1:47 | 03:59:00 |
|    2:12 |     1:47 |    03:59 |
| 3:02:20 | -2:07:00 |     0.92 |
,#+TBLFM: @2$3=$1+$2;T::@3$3=$1+$2;U::@4$3=$1+$2;t
#+end_example

Input duration values must be of the form =HH:MM[:SS]=, where seconds
are optional.  With the =T= flag, computed durations are displayed as
=HH:MM:SS= (see the first formula above).  With the =U= flag, seconds
are omitted so that the result is only =HH:MM= (see second formula
above).  Zero-padding of the hours field depends upon the value of the
variable ~org-table-duration-hour-zero-padding~.

With the =t= flag, computed durations are displayed according to the
value of the option ~org-table-duration-custom-format~, which defaults
to ~hours~ and displays the result as a fraction of hours (see the
third formula in the example above).

Negative duration values can be manipulated as well, and integers are
considered as seconds in addition and subtraction.

