#+chunk-id: org-manual-chunk-0168
#+source-file: org-manual
#+heading-path: Citation handling > Bibliography printing > Bibliography options in the =biblatex= and =csl= export processors
#+start-line: 18008
#+end-line: 18052
#+external-urls: 
#+mirrored-urls: 
*** Bibliography options in the =biblatex= and =csl= export processors

The =biblatex= and =csl= export processors support bibliography
options through a property list attached to the =PRINT_BIBLIOGRAPHY=
keyword.  For example,

: #+print_bibliography: :keyword algebra :type book

Values including spaces must be surrounded with double quotes.  If you
need to use a key multiple times, you can separate its values with
commas, but without any space in-between:

: #+print_bibliography: :keyword "algebraic logic" :nottype article,book

The =biblatex= export processor accepts all options supported by
BibLaTeX's ~\printbibliography~ command.

The =csl= processor accepts the following options:

- =:keyword <keyword(,keyword2...)>= :: Print only entries whose
  keyword field contains all given keywords.

- =:notkeyword <keyword(,keyword2...)>= :: Print only entries whose
  keyword field does not contain any of the given keywords.

- =:type <entrytype>= :: Print only entries whose type is
  =<entrytype>=.  Entry type is the BibTeX/BibLaTeX entry type if this
  information is available (the entry was read from a BibTeX/BibLaTeX
  bibliography) and the CSL entry type otherwise.

- =:nottype <entrytype(,entrytype2...)>= :: Print only entries whose
  type is not among the given entry types.  Entry type is determined
  as in the case of =:type=.

- =:csltype <entrytype>= :: Print only entries whose CSL entry type
  (possibly based on a conversion from BibTeX/BibLaTeX to CSL) is
  =<entrytype>=.

- =:notcsltype <entrytype(,entrytype2...)>= :: Print only entries whose
  CSL entry type (possibly based on a conversion from BibTeX/BibLaTeX
  to CSL) is not among the listed entry types.

- =:filter <predicate>= :: Print only entries for which the given
  Emacs Lisp predicate returns a non-~nil~ value.

