#+chunk-id: org-manual-chunk-0034
#+source-file: org-manual
#+heading-path: TODO Items > Extended Use of TODO Keywords > Setting up keywords for individual files
#+start-line: 4192
#+end-line: 4239
#+external-urls: 
#+mirrored-urls: 
*** Setting up keywords for individual files
:PROPERTIES:
:DESCRIPTION: Different files, different requirements.
:ALT_TITLE: Per-file keywords
:END:
#+cindex: keyword options
#+cindex: per-file keywords
#+cindex: @samp{TODO}, keyword
#+cindex: @samp{TYP_TODO}, keyword
#+cindex: @samp{SEQ_TODO}, keyword

It can be very useful to use different aspects of the TODO mechanism
in different files.  For file-local settings, you need to add special
lines to the file which set the keywords and interpretation for that
file only.  For example, to set one of the two examples discussed
above, you need one of the following lines, starting in column zero
anywhere in the file:

: #+TODO: TODO FEEDBACK VERIFY | DONE CANCELED

You may also write =#+SEQ_TODO= to be explicit about the
interpretation, but it means the same as =#+TODO=, or

: #+TYP_TODO: Fred Sara Lucy Mike | DONE

A setup for using several sets in parallel would be:

#+begin_example
,#+TODO: TODO(t) | DONE(d)
,#+TODO: REPORT(r) BUG(b) KNOWNCAUSE(k) | FIXED(f)
,#+TODO: | CANCELED(c)
#+end_example

#+cindex: completion, of option keywords
#+kindex: M-TAB
To make sure you are using the correct keyword, type =#+= into the
buffer and then use {{{kbd(M-TAB)}}} to complete it (see [[*Completion]]).

#+cindex: DONE, final TODO keyword
Remember that the keywords after the vertical bar---or the last
keyword if no bar is there---must always mean that the item is DONE,
although you may use a different word.  After changing one of these
lines, use {{{kbd(C-c C-c)}}} with point still in the line to make the
changes known to Org mode[fn:: Org mode parses these lines only when
Org mode is activated after visiting a file. {{{kbd(C-c C-c)}}} with
point in a line starting with =#+= is simply restarting Org mode for
the current buffer.].

