#+chunk-id: org-manual-chunk-0126
#+source-file: org-manual
#+heading-path: Exporting > OpenDocument Text Export > ODT export commands
#+start-line: 15091
#+end-line: 15127
#+external-urls: 
#+mirrored-urls: 
*** ODT export commands
:PROPERTIES:
:DESCRIPTION: Invoking export.
:END:

- {{{kbd(C-c C-e o o)}}} (~org-odt-export-to-odt~) ::

  #+kindex: C-c C-e o o
  #+findex: org-odt-export-to-odt
  Export as OpenDocument Text file.

  #+cindex: @samp{EXPORT_FILE_NAME}, property
  #+vindex: org-odt-preferred-output-format

  If ~org-odt-preferred-output-format~ is specified, the ODT export
  backend automatically converts the exported file to that format.

  For =myfile.org=, Org exports to =myfile.odt=, overwriting without
  warning.  The ODT export backend exports a region only if a region
  was active.

  If the selected region is a single tree, the ODT export backend
  makes the tree head the document title.  Incidentally, {{{kbd(C-c
  @)}}} selects the current subtree.  If the tree head entry has, or
  inherits, an =EXPORT_FILE_NAME= property, the ODT export backend
  uses that for file name.

- {{{kbd(C-c C-e o O)}}} ::

  #+kindex: C-c C-e o O
  Export as an OpenDocument Text file and open the resulting file.

  #+vindex: org-export-odt-preferred-output-format
  If ~org-export-odt-preferred-output-format~ is specified, open the
  converted file instead.  See [[*Automatically exporting to other
  formats]].

