#+chunk-id: org-manual-chunk-0073
#+source-file: org-manual
#+heading-path: Agenda Views > Commands in the Agenda Buffer > Bulk remote editing selected entries
#+start-line: 10621
#+end-line: 10751
#+external-urls: 
#+mirrored-urls: 
*** Bulk remote editing selected entries
:PROPERTIES:
:UNNUMBERED: notoc
:END:
#+cindex: remote editing, bulk, from agenda
#+vindex: org-agenda-bulk-custom-functions

- {{{kbd(m)}}} (~org-agenda-bulk-mark~) ::
  #+kindex: m
  #+findex: org-agenda-bulk-mark

  Mark the entry at point for bulk action.  If there is an active
  region in the agenda, mark the entries in the region.  With numeric
  prefix argument, mark that many successive entries.

- {{{kbd(*)}}} (~org-agenda-bulk-mark-all~) ::
  #+kindex: *
  #+findex: org-agenda-bulk-mark-all

  Mark all visible agenda entries for bulk action.

- {{{kbd(u)}}} (~org-agenda-bulk-unmark~) ::
  #+kindex: u
  #+findex: org-agenda-bulk-unmark

  Unmark entry for bulk action.

- {{{kbd(U)}}} (~org-agenda-bulk-unmark-all~) ::
  #+kindex: U
  #+findex: org-agenda-bulk-unmark-all

  Unmark all marked entries for bulk action.

- {{{kbd(M-m)}}} (~org-agenda-bulk-toggle~) ::
  #+kindex: M-m
  #+findex: org-agenda-bulk-toggle

  Toggle mark of the entry at point for bulk action.

- {{{kbd(M-*)}}} (~org-agenda-bulk-toggle-all~) ::
  #+kindex: M-*
  #+findex: org-agenda-bulk-toggle-all

  Toggle mark of every entry for bulk action.

- {{{kbd(%)}}} (~org-agenda-bulk-mark-regexp~) ::
  #+kindex: %
  #+findex: org-agenda-bulk-mark-regexp

  Mark entries matching a regular expression for bulk action.

- {{{kbd(B)}}} (~org-agenda-bulk-action~) ::
  #+kindex: B
  #+findex: org-agenda-bulk-action
  #+vindex: org-agenda-bulk-persistent-marks

  Bulk action: act on all marked entries in the agenda.  This prompts
  for another key to select the action to be applied.  The prefix
  argument to {{{kbd(B)}}} is passed through to the {{{kbd(s)}}} and
  {{{kbd(d)}}} commands, to bulk-remove these special timestamps.  By
  default, marks are removed after the bulk.  If you want them to
  persist, set ~org-agenda-bulk-persistent-marks~ to ~t~ or hit
  {{{kbd(p)}}} at the prompt.

  - {{{kbd(p)}}} ::

    Toggle persistent marks.

  - {{{kbd($)}}} ::

    Archive all selected entries.

  - {{{kbd(A)}}} ::

    Archive entries by moving them to their respective archive
    siblings.

  - {{{kbd(t)}}} ::

    Change TODO state.  This prompts for a single TODO keyword and
    changes the state of all selected entries, bypassing blocking and
    suppressing logging notes---but not timestamps.

  - {{{kbd(+)}}} ::

    Add a tag to all selected entries.

  - {{{kbd(-)}}} ::

    Remove a tag from all selected entries.

  - {{{kbd(s)}}} ::

    Schedule all items to a new date.  To shift existing schedule
    dates by a fixed number of days, use something starting with
    double plus at the prompt, for example =++8d= or =++2w=.

  - {{{kbd(d)}}} ::

    Set deadline to a specific date.

  - {{{kbd(r)}}} ::

    Prompt for a single refile target and move all entries.  The
    entries are no longer in the agenda; refresh ({{{kbd(g)}}}) to
    bring them back.

  - {{{kbd(S)}}} ::

    Reschedule randomly into the coming N days.  N is prompted for.
    With a prefix argument ({{{kbd(C-u B S)}}}), scatter only across
    weekdays.

  - {{{kbd(f)}}} ::

    #+vindex: org-agenda-bulk-custom-functions
    Apply a function[fn:: You can also create persistent custom
    functions through ~org-agenda-bulk-custom-functions~.] to marked
    entries.  For example, the function below sets the =CATEGORY=
    property of the entries to =web=.

    #+begin_src emacs-lisp
    (defun set-category ()
      (interactive "P")
      (let ((marker (or (org-get-at-bol 'org-hd-marker)
                        (org-agenda-error))))
        (org-with-point-at marker
          (org-back-to-heading t)
          (org-set-property "CATEGORY" "web"))))
    #+end_src

