#+chunk-id: org-manual-chunk-0091
#+source-file: org-manual
#+heading-path: Exporting > Beamer Export > Frames and Blocks in Beamer
#+start-line: 13199
#+end-line: 13272
#+external-urls: 
#+mirrored-urls: 
*** Frames and Blocks in Beamer
:PROPERTIES:
:DESCRIPTION: For composing Beamer slides.
:END:

Org transforms heading levels into Beamer's sectioning elements,
frames and blocks.  Any Org tree with a not-too-deep-level nesting
should in principle be exportable as a Beamer presentation.

-
  #+vindex: org-beamer-frame-level
  Org headlines become Beamer frames when the heading level in Org is
  equal to ~org-beamer-frame-level~ or =H= value in a =OPTIONS= line
  (see [[*Export Settings]]).

  #+cindex: @samp{BEAMER_ENV}, property
  Org overrides headlines to frames conversion for the current tree of
  an Org file if it encounters the =BEAMER_ENV= property set to
  =frame= or =fullframe=.  Org ignores whatever
  ~org-beamer-frame-level~ happens to be for that headline level in
  the Org tree.  In Beamer terminology, a full frame is a frame
  without its title.

- Org exports a Beamer frame's objects as block environments.  Org can
  enforce wrapping in special block types when =BEAMER_ENV= property
  is set[fn:46].  For valid values see
  ~org-beamer-environments-default~.  To add more values, see
  ~org-beamer-environments-extra~.
  #+vindex: org-beamer-environments-default
  #+vindex: org-beamer-environments-extra

-
  #+cindex: @samp{BEAMER_REF}, property
  If =BEAMER_ENV= is set to =appendix=, Org exports the entry as an
  appendix.  When set to =note=, Org exports the entry as a note
  within the frame or between frames, depending on the entry's heading
  level.  When set to =noteNH=, Org exports the entry as a note
  without its title.  When set to =againframe=, Org exports the entry
  with =\againframe= command, which makes setting the =BEAMER_REF=
  property mandatory because =\againframe= needs frame to resume.

  When =ignoreheading= is set, Org export ignores the entry's headline
  but not its content.  This is useful for inserting content between
  frames.  It is also useful for properly closing a =column=
  environment.

  #+cindex: @samp{BEAMER_SUBTITLE}, property
  If =BEAMER_SUBTITLE= is set, Org exports its value as the subtitle
  for the headline's frame. This property has no effect on headlines
  which are not exported as frames.

  #+cindex: @samp{BEAMER_ACT}, property
  #+cindex: @samp{BEAMER_OPT}, property
  When =BEAMER_ACT= is set for a headline, Org export translates that
  headline as an overlay or action specification.  When enclosed in
  square brackets, Org export makes the overlay specification
  a default.  Use =BEAMER_OPT= to set any options applicable to the
  current Beamer frame or block.  The Beamer export backend wraps
  with appropriate angular or square brackets.  It also adds the
  =fragile= option for any code that may require a verbatim block.

  #+cindex: @samp{BEAMER_COL}, property
  To create a column on the Beamer slide, use the =BEAMER_COL=
  property for its headline in the Org file.  Set the value of
  =BEAMER_COL= to a decimal number representing the fraction of the
  total text width.  Beamer export uses this value to set the column's
  width and fills the column with the contents of the Org entry.  If
  the Org entry has no specific environment defined, Beamer export
  ignores the heading.  If the Org entry has a defined environment,
  Beamer export uses the heading as title.  Behind the scenes, Beamer
  export automatically handles LaTeX column separations for contiguous
  headlines.  To manually adjust them for any unique configurations
  needs, use the =BEAMER_ENV= property.

