#+chunk-id: org-manual-chunk-0028
#+source-file: org-manual
#+heading-path: Tables > Org Plot > Graphical plots using Gnuplot
#+start-line: 2962
#+end-line: 3102
#+external-urls: http://cars9.uchicago.edu/~ravel/software/gnuplot-mode.html, https://orgmode.org/worg/org-tutorials/org-plot.html, https://www.gnuplot.info/
#+mirrored-urls: https://orgmode.org/worg/org-tutorials/org-plot.html
*** Graphical plots using Gnuplot
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+cindex: @samp{PLOT}, keyword
Org Plot can produce 2D and 3D graphs of information stored in Org
tables using [[https://www.gnuplot.info/][Gnuplot]] and [[http://cars9.uchicago.edu/~ravel/software/gnuplot-mode.html][Gnuplot mode]].  To see this in action, ensure
that you have both Gnuplot and Gnuplot mode installed on your system,
then call {{{kbd(C-c \quot g)}}} or {{{kbd(M-x org-plot/gnuplot)}}} on the
following table.

#+begin_example
,#+PLOT: title:"Citas" ind:1 deps:(3) type:2d with:histograms set:"yrange [0:]"
| Sede      | Max cites | H-index |
|-----------+-----------+---------|
| Chile     |    257.72 |   21.39 |
| Leeds     |    165.77 |   19.68 |
| Sao Paolo |     71.00 |   11.50 |
| Stockholm |    134.19 |   14.33 |
| Morelia   |    257.56 |   17.67 |
#+end_example

Org Plot supports a range of plot types, and provides the ability to add more.
For example, a radar plot can be generated like so:
#+begin_example
,#+PLOT: title:"An evaluation of plaintext document formats" transpose:yes type:radar min:0 max:4
| Format            | Fine-grained-control | Initial Effort | Syntax simplicity | Editor Support | Integrations | Ease-of-referencing | Versatility |
|-------------------+----------------------+----------------+-------------------+----------------+--------------+---------------------+-------------|
| Word              |                    2 |              4 |                 4 |              2 |            3 |                   2 |           2 |
| LaTeX             |                    4 |              1 |                 1 |              3 |            2 |                   4 |           3 |
| Org Mode          |                    4 |              2 |               3.5 |              1 |            4 |                   4 |           4 |
| Markdown          |                    1 |              3 |                 3 |              4 |            3 |                   3 |           1 |
| Markdown + Pandoc |                  2.5 |            2.5 |               2.5 |              3 |            3 |                   3 |           2 |
#+end_example

Notice that Org Plot is smart enough to apply the table's headers as
labels.  Further control over the labels, type, content, and
appearance of plots can be exercised through the =PLOT= keyword
preceding a table.  See below for a complete list of Org Plot options.
For more information and examples see the [[../../mirror/by-url/5c9484f8eb695e59a1aa801d263be0247b6a8aba862f4b670e97159273573a64.html][Org Plot tutorial]].

**** Plot options
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- =set= ::

  Specify any Gnuplot option to be set when graphing.

- =title= ::

  Specify the title of the plot.

- =ind= ::

  Specify which column of the table to use as the =x= axis.

- =timeind= ::

  Specify which column of the table to use as the =x= axis as a time
  value.

- =deps= ::

  Specify the columns to graph as a Lisp style list, surrounded by
  parentheses and separated by spaces for example =dep:(3 4)= to graph
  the third and fourth columns.  Defaults to graphing all other
  columns aside from the =ind= column.

- =transpose= ::

  When =y=, =yes=, or =t= attempt to transpose the table data before
  plotting.  Also recognizes the shorthand option =trans=.

- =type= ::

  Specify the type of the plot, by default one of  =2d=, =3d=, =radar=, or =grid=.
  Available types can be customized with ~org-plot/preset-plot-types~.

- =with= ::

  Specify a =with= option to be inserted for every column being
  plotted, e.g., =lines=, =points=, =boxes=, =impulses=.  Defaults to
  =lines=.

- =file= ::

  If you want to plot to a file, specify
  ="path/to/desired/output-file"=.

- =labels= ::

  List of labels to be used for the =deps=.  Defaults to the column
  headers if they exist.

- =line= ::

  Specify an entire line to be inserted in the Gnuplot script.

- =map= ::

  When plotting =3d= or =grid= types, set this to =t= to graph a flat
  mapping rather than a =3d= slope.

- =min= ::

  Provides a minimum axis value that may be used by a plot type.
  Implicitly assumes the =y= axis is being referred to.  You can
  explicitly provide a value for the =x= or =y= axis with =xmin= and
  =ymin=.

- =max= ::

  Provides a maximum axis value that may be used by a plot type.
  Implicitly assumes the =y= axis is being referred to.  You can
  explicitly provide a value for the =x= or =y= axis with =xmax= and
  =ymax=.

- =ticks= ::

  Provides a desired number of axis ticks to display, that may be used
  by a plot type.  If none is given a plot type that requires ticks
  will use ~org--plot/sensible-tick-num~ to try to determine a good
  value.

- =timefmt= ::

  Specify format of Org mode timestamps as they will be parsed by
  Gnuplot.  Defaults to =%Y-%m-%d-%H:%M:%S=.

- =script= ::

  If you want total control, you can specify a script file---place the
  file name between double-quotes---which will be used to plot.
  Before plotting, every instance of =$datafile= in the specified
  script will be replaced with the path to the generated data file.
  Note: even if you set this option, you may still want to specify the
  plot type, as that can impact the content of the data file.

