#+chunk-id: org-manual-chunk-0111
#+source-file: org-manual
#+heading-path: Exporting > LaTeX Export > LaTeX header and sectioning structure
#+start-line: 14303
#+end-line: 14437
#+external-urls: https://mirrors.ctan.org/macros/latex/required/babel/base/babel.pdf
#+mirrored-urls: https://mirrors.ctan.org/macros/latex/required/babel/base/babel.pdf
*** LaTeX header and sectioning structure
:PROPERTIES:
:DESCRIPTION: Setting up the export file structure.
:ALT_TITLE: LaTeX header and sectioning
:END:
#+cindex: @LaTeX{} class
#+cindex: @LaTeX{} sectioning structure
#+cindex: @LaTeX{} header
#+cindex: header, for @LaTeX{} files
#+cindex: sectioning structure, for @LaTeX{} export

The LaTeX export backend converts the first three of Org's outline
levels into LaTeX headlines.  The remaining Org levels are exported as
lists.  To change this globally for the cut-off point between levels
and lists, (see [[*Export Settings]]).

By default, the LaTeX export backend uses the /article/ class.

#+vindex: org-latex-default-class
#+vindex: org-latex-classes
#+vindex: org-latex-default-packages-alist
#+vindex: org-latex-packages-alist
To change the default class globally, edit ~org-latex-default-class~.
To change the default class locally in an Org file, add option lines
=#+LATEX_CLASS: myclass=.  To change the default class for just a part
of the Org file, set a subtree property, =EXPORT_LATEX_CLASS=.  The
class name entered here must be valid member of ~org-latex-classes~.
This variable defines a header template for each class into which the
exporter splices the values of ~org-latex-default-packages-alist~ and
~org-latex-packages-alist~.  Use the same three variables to define
custom sectioning or custom classes.

#+cindex: @samp{LATEX_CLASS}, keyword
#+cindex: @samp{LATEX_CLASS_OPTIONS}, keyword
#+cindex: @samp{EXPORT_LATEX_CLASS}, property
#+cindex: @samp{EXPORT_LATEX_CLASS_OPTIONS}, property
The LaTeX export backend sends the =LATEX_CLASS_OPTIONS= keyword and
=EXPORT_LATEX_CLASS_OPTIONS= property as options to the LaTeX
~\documentclass~ macro.  The options and the syntax for specifying
them, including enclosing them in square brackets, follow LaTeX
conventions.

: #+LATEX_CLASS_OPTIONS: [a4paper,11pt,twoside,twocolumn]

#+cindex: @samp{LATEX_HEADER}, keyword
#+cindex: @samp{LATEX_HEADER_EXTRA}, keyword
The LaTeX export backend appends values from =LATEX_HEADER= and
=LATEX_HEADER_EXTRA= keywords to the LaTeX header.  The docstring for
~org-latex-classes~ explains in more detail.  Also note that LaTeX
export backend does not append =LATEX_HEADER_EXTRA= to the header
when previewing LaTeX snippets (see [[*Previewing LaTeX fragments]]).

A sample Org file with the above headers:

#+begin_example
,#+LATEX_CLASS: article
,#+LATEX_CLASS_OPTIONS: [a4paper]
,#+LATEX_HEADER: \usepackage{xyz}

,* Headline 1
  some text
,* Headline 2
  some more text
#+end_example

#+cindex: @samp{LATEX_CLASS_PRE}, keyword
The LaTeX export backend prepends values from =LATEX_CLASS_PRE=
keywords before the LaTeX preamble. Use this option when you want to
set the values passed to packages included in the document class. For
example, to use extended names for the ~xcolor~ package, use

#+begin_example
,#+LATEX_CLASS_PRE: \PassOptionsToPackage{dvipsnames}{xcolor}
#+end_example

#+cindex: @samp{LANGUAGE}, keyword
#+vindex: org-export-default-language
LaTeX packages =babel= or =polyglossia= can also be loaded in a
document.  The "AUTO" string will be replaced in both cases by the
appropriate value for the =LANGUAGE= keyword, if present in the
document, or by the value of ~org-export-default-language~.  Let's see
some examples in one or another case.

=Babel= accepts the classic syntax and (in addition) the new syntax
with the =\babelprovide= command to load the languages using the new
=INI= files procedure.  Keep in mind that there are a number of
languages that are only served in babel using =INI= files, so they
cannot be declared using the classic syntax, but only using the
=\babelprovide= command (see
../../mirror/by-url/d46a193794f241fab2caadcde2987faef5f47dcaccf47682f9631f302577df62.pdf).
Valid usage examples could be:

#+begin_example
,#+LATEX_HEADER: \usepackage[french,italian,AUTO]{babel}
#+end_example

where "AUTO" is the main language.  But it can also be loaded using
the =\babelprovide= command:

#+begin_example
,#+LATEX_HEADER: \usepackage[french,italian]{babel}
,#+LATEX_HEADER: \babelprovide[import, main]{AUTO}
#+end_example

=Polyglossia=, for this procedure to be effective, must be loaded
using the same =babel= classic syntax (but note that /this is not/
the actual polyglossia syntax).  For example, suppose a document
declares Polytonic Greek as the primary language, and French as the
secondary language.  In this case, it would be expressed as:

#+begin_example
,#+LANGUAGE: el-polyton
,#+LATEX_HEADER: \usepackage[french,AUTO]{polyglossia}
#+end_example

This would produce in LaTeX (with the actual =polyglossia= syntax):

#+begin_example
\usepackage{polyglossia}
\setmainlanguage[variant=polytonic]{greek}
\setotherlanguage{french}
#+end_example

#+vindex: org-latex-use-sans
The LaTeX backend normally exports using the Roman font family
specified in the document class or by the user in the
=LATEX_HEADER=. Setting the option ~org-latex-use-sans~ to =t= will
force the LaTeX compiler to use the Sans font as default. You can also
include it in the document options with:

#+begin_example
#+OPTIONS: latex-use-sans:t
#+end_example


