#+chunk-id: org-manual-chunk-0092
#+source-file: org-manual
#+heading-path: Exporting > Beamer Export > Beamer specific syntax
#+start-line: 13273
#+end-line: 13336
#+external-urls: 
#+mirrored-urls: 
*** Beamer specific syntax
:PROPERTIES:
:DESCRIPTION: For using in Org documents.
:END:

Since Org's Beamer export backend is an extension of the LaTeX
backend, it recognizes other LaTeX specific syntax---for example,
=#+LATEX:= or =#+ATTR_LATEX:=.  See [[*LaTeX Export]], for details.

Beamer export wraps the table of contents generated with =toc:t=
=OPTION= keyword in a =frame= environment.  Beamer export does not
wrap the table of contents generated with =TOC= keyword (see [[*Table of
Contents]]).  Use square brackets for specifying options.

: #+TOC: headlines [currentsection]

Insert Beamer-specific code using the following constructs:

#+cindex: @samp{BEAMER}, keyword
#+cindex: @samp{BEGIN_EXPORT beamer}
#+begin_example
,#+BEAMER: \pause

,#+BEGIN_EXPORT beamer
  Only Beamer export backend exports this.
,#+END_EXPORT

Text @@beamer:some code@@ within a paragraph.
#+end_example

Inline constructs, such as the last one above, are useful for adding
overlay specifications to objects with ~bold~, ~item~, ~link~,
~radio-target~ and ~target~ types.  Enclose the value in angular
brackets and place the specification at the beginning of the object as
shown in this example:

:  A *@@beamer:<2->@@useful* feature

#+cindex: @samp{ATTR_BEAMER}, keyword
Beamer export recognizes the =ATTR_BEAMER= keyword with the following
attributes from Beamer configurations: =:environment= for changing
local Beamer environment, =:overlay= for specifying Beamer overlays in
angular or square brackets, and =:options= for inserting optional
arguments.

#+begin_example
,#+ATTR_BEAMER: :environment nonindentlist
- item 1, not indented
- item 2, not indented
- item 3, not indented
#+end_example

#+begin_example
,#+ATTR_BEAMER: :overlay <+->
- item 1
- item 2
#+end_example

#+begin_example
,#+ATTR_BEAMER: :options [Lagrange]
Let $G$ be a finite group, and let $H$ be
a subgroup of $G$.  Then the order of $H$ divides the order of $G$.
#+end_example

