#+chunk-id: org-manual-chunk-0012
#+source-file: org-manual
#+heading-path: Tables > Built-in Table Editor > Creation and conversion
#+start-line: 1467
#+end-line: 1490
#+external-urls: 
#+mirrored-urls: 
*** Creation and conversion
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- {{{kbd(C-c |)}}} (~org-table-create-or-convert-from-region~) ::

  #+kindex: C-c |
  #+findex: org-table-create-or-convert-from-region
  Convert the active region to table.  If every line contains at least
  one {{{kbd(TAB)}}} character, the function assumes that the material
  is tab separated.  If every line contains a comma, comma-separated
  values (CSV) are assumed.  If not, lines are split at whitespace
  into fields.  You can use a prefix argument to force a specific
  separator: {{{kbd(C-u)}}} forces CSV, {{{kbd(C-u C-u)}}} forces
  {{{kbd(TAB)}}}, {{{kbd(C-u C-u C-u)}}} prompts for a regular
  expression to match the separator, and a numeric argument
  N indicates that at least N consecutive spaces, or alternatively
  a {{{kbd(TAB)}}} will be the separator.

  If there is no active region, this command creates an empty Org
  table.  But it is easier just to start typing, like {{{kbd(|
  N a m e | P h o n e | A g e RET | - TAB)}}}.

