#+chunk-id: org-manual-chunk-0187
#+source-file: org-manual
#+heading-path: Working with Source Code > Extracting Source Code > Tangle hooks
#+start-line: 19761
#+end-line: 19790
#+external-urls: 
#+mirrored-urls: 
*** Tangle hooks
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- ~org-babel-pre-tangle-hook~ ::

  #+vindex: org-babel-pre-tangle-hook
  This hook is run before the tangle process begins.  The active
  buffer is buffer to be tangled.

- ~org-babel-tangle-body-hook~ ::

  #+vindex: org-babel-tangle-body-hook
  This hook is run from a temporary buffer containing expanded code of
  every tangled code block.  The hook can modify the expanded code as
  needed.  The contents of the current buffer will be used as actual
  code block expansion.

- ~org-babel-post-tangle-hook~ ::

  #+vindex: org-babel-post-tangle-hook
  This hook is run from within code files tangled by
  ~org-babel-tangle~, making it suitable for post-processing,
  compilation, and evaluation of code in the tangled files.

- ~org-babel-tangle-finished-hook~ ::
  #+vindex: org-babel-tangle-finished-hook
  This hook is run after post-tangle hooks, in the original buffer.

