#+chunk-id: org-manual-chunk-0158
#+source-file: org-manual
#+heading-path: Publishing > Configuration > The variable ~org-publish-project-alist~
#+start-line: 17194
#+end-line: 17227
#+external-urls: 
#+mirrored-urls: 
*** The variable ~org-publish-project-alist~
:PROPERTIES:
:DESCRIPTION: The central configuration variable.
:ALT_TITLE: Project alist
:END:
#+cindex: projects, for publishing

#+vindex: org-publish-project-alist
Publishing is configured almost entirely through setting the value of
one variable, called ~org-publish-project-alist~.  Each element of the
list configures one project, and may be in one of the two following
forms:

#+begin_src emacs-lisp
("project-name" :property value :property value ...)
#+end_src

#+texinfo: @noindent
i.e., a well-formed property list with alternating keys and values,
or:

#+begin_src emacs-lisp
("project-name" :components ("project-name" "project-name" ...))
#+end_src

In both cases, projects are configured by specifying property values.
A project defines the set of files that are to be published, as well
as the publishing configuration to use when publishing those files.
When a project takes the second form listed above, the individual
members of the ~:components~ property are taken to be sub-projects,
which group together files requiring different publishing options.
When you publish such a "meta-project", all the components are also
published, in the sequence given.

