#+chunk-id: org-manual-chunk-0170
#+source-file: org-manual
#+heading-path: Working with Source Code > Using Header Arguments > Header arguments in Org mode properties
#+start-line: 18304
#+end-line: 18367
#+external-urls: 
#+mirrored-urls: 
*** Header arguments in Org mode properties
:PROPERTIES:
:UNNUMBERED: notoc
:END:

For header arguments applicable to the buffer, use =PROPERTY= keyword
anywhere in the Org file (see [[*Property Syntax]]).

The following example makes all the R code blocks execute in the same
session.  Setting =:results= to =silent= ignores the results of
executions for all blocks, not just R code blocks; no results inserted
for any block.

#+begin_example
,#+PROPERTY: header-args:R  :session *R*
,#+PROPERTY: header-args    :results silent
#+end_example

#+vindex: org-use-property-inheritance
Header arguments set through Org's property drawers (see [[*Property
Syntax]]) apply at the subtree level on down.  Since these property
drawers can appear anywhere in the file hierarchy, Org uses outermost
call or source block to resolve the values.  Org ignores
~org-use-property-inheritance~ setting.

In this example, =:cache= defaults to =yes= for all code blocks in the
subtree.

#+begin_example
,* sample header
  :PROPERTIES:
  :header-args:    :cache yes
  :END:
#+end_example

#+kindex: C-c C-x p
#+findex: org-set-property
Properties defined through ~org-set-property~ function, bound to
{{{kbd(C-c C-x p)}}}, apply to all active languages.  They override
properties set in ~org-babel-default-header-args~.

#+cindex: language-specific header arguments properties
#+cindex: header arguments per language
Language-specific header arguments are also read from properties
=header-args:<LANG>= where {{{var(<LANG>)}}} is the language
identifier.  For example,

#+begin_example
,* Heading
  :PROPERTIES:
  :header-args:clojure:    :session *clojure-1*
  :header-args:R:          :session *R*
  :END:
,** Subheading
  :PROPERTIES:
  :header-args:clojure:    :session *clojure-2*
  :END:
#+end_example

#+texinfo: @noindent
would force separate sessions for Clojure blocks in =Heading= and
=Subheading=, but use the same session for all R blocks.  Blocks in
=Subheading= inherit settings from =Heading=.

