#+chunk-id: org-manual-chunk-0032
#+source-file: org-manual
#+heading-path: TODO Items > Extended Use of TODO Keywords > Multiple keyword sets in one file
#+start-line: 4118
#+end-line: 4168
#+external-urls: 
#+mirrored-urls: 
*** Multiple keyword sets in one file
:PROPERTIES:
:DESCRIPTION: Mixing it all, still finding your way.
:ALT_TITLE: Multiple sets in one file
:END:
#+cindex: TODO keyword sets

Sometimes you may want to use different sets of TODO keywords in
parallel.  For example, you may want to have the basic TODO/DONE, but
also a workflow for bug fixing, and a separate state indicating that
an item has been canceled---so it is not DONE, but also does not
require action.  Your setup would then look like this:

#+begin_src emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO" "|" "DONE")
        (sequence "REPORT" "BUG" "KNOWNCAUSE" "|" "FIXED")
        (sequence "|" "CANCELED")))
#+end_src

The keywords should all be different, this helps Org mode keep track
of which subsequence should be used for a given entry.  In this setup,
{{{kbd(C-c C-t)}}} only operates within a sub-sequence, so it switches
from =DONE= to (nothing) to =TODO=, and from =FIXED= to (nothing) to
=REPORT=.  Therefore, you need a mechanism to initially select the
correct sequence.  In addition to typing a keyword or using completion
(see [[*Completion]]), you may also apply the following commands:

#+attr_texinfo: :sep ,
- {{{kbd(C-u C-u C-c C-t)}}}, {{{kbd(C-S-RIGHT)}}}, {{{kbd(C-S-LEFT)}}} ::

  #+kindex: C-S-RIGHT
  #+kindex: C-S-LEFT
  #+kindex: C-u C-u C-c C-t
  These keys jump from one TODO sub-sequence to the next.  In the
  above example, {{{kbd(C-u C-u C-c C-t)}}} or {{{kbd(C-S-RIGHT)}}}
  would jump from =TODO= or =DONE= to =REPORT=, and any of the words
  in the second row to =CANCELED=.  Note that the {{{kbd(C-S-)}}} key
  binding conflict with shift-selection (see [[*Packages that conflict
  with Org mode]]).

- {{{kbd(S-RIGHT)}}}, {{{kbd(S-LEFT)}}} ::

  #+kindex: S-RIGHT
  #+kindex: S-LEFT
  {{{kbd(S-LEFT)}}} and {{{kbd(S-RIGHT)}}} walk through /all/ keywords
  from all sub-sequences, so for example {{{kbd(S-RIGHT)}}} would
  switch from =DONE= to =REPORT= in the example above.  For
  a discussion of the interaction with shift-selection, see [[*Packages
  that conflict with Org mode]].

