#+chunk-id: org-manual-chunk-0181
#+source-file: org-manual
#+heading-path: Working with Source Code > Results of Evaluation > Type
#+start-line: 19159
#+end-line: 19290
#+external-urls: 
#+mirrored-urls: 
*** Type
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Type tells what result types to expect from the execution of the code
block.  Choose one of the options; they are mutually exclusive.

The default behavior is to automatically determine the result type.
The result type detection depends on the code block language, as
described in the documentation for individual languages.  See
[[*Languages]].

#+attr_texinfo: :sep ,
- =table=, =vector= ::

  Interpret the results as an Org table.  If the result is a single
  value, create a table with one row and one column.  Usage example:
  =:results value table=.

  #+cindex: @samp{hlines}, header argument
  In-between each table row or below the table headings, sometimes
  results have horizontal lines, which are also known as "hlines".
  The =hlines= argument with the default =no= value strips such lines
  from the input table.  For most code, this is desirable, or else
  those =hline= symbols raise unbound variable errors.  A =yes=
  accepts such lines, as demonstrated in the following example.

  # We keep python blocks unindented on purpose - to keep the example
  # working even for users who changed the default value of ~org-src-preserve-indentation~
  #+begin_example
  ,#+NAME: many-cols
  | a | b | c |
  |---+---+---|
  | d | e | f |
  |---+---+---|
  | g | h | i |

  ,#+NAME: no-hline
  ,#+BEGIN_SRC python :var tab=many-cols :hlines no
  return tab
  ,#+END_SRC

  ,#+RESULTS: no-hline
  | a | b | c |
  | d | e | f |
  | g | h | i |

  ,#+NAME: hlines
  ,#+BEGIN_SRC python :var tab=many-cols :hlines yes
  return tab
  ,#+END_SRC

  ,#+RESULTS: hlines
  | a | b | c |
  |---+---+---|
  | d | e | f |
  |---+---+---|
  | g | h | i |
  #+end_example

- =list= ::

  Interpret the results as an Org list.  If the result is a single
  value, create a list of one element.

- =scalar=, =verbatim= ::

  Interpret literally and insert as quoted text.  Do not create
  a table.  Usage example: =:results value verbatim=.

- =file= ::

  Interpret as a filename.  Save the results of execution of the code
  block to that file, then insert a link to it.  You can control both
  the filename and the description associated to the link.

  #+cindex: @samp{file}, header argument
  #+cindex: @samp{output-dir}, header argument
  Org first tries to generate the filename from the value of the
  =file= header argument and the directory specified using the
  =output-dir= header arguments.  If =output-dir= is not specified,
  Org assumes it is the current directory.

  #+begin_example
  ,#+BEGIN_SRC asymptote :results value file :file circle.pdf :output-dir img/
    size(2cm);
    draw(unitcircle);
  ,#+END_SRC
  #+end_example

  #+cindex: @samp{file-ext}, header argument
  If =file= header argument is missing, Org generates the base name of
  the output file from the name of the code block, and its extension
  from the =file-ext= header argument.  In that case, both the name
  and the extension are mandatory.

  Result can also be interpreted as path to file.  See =:results
  link=.

  #+begin_example
  ,#+name: circle
  ,#+BEGIN_SRC asymptote :results value file :file-ext pdf
    size(2cm);
    draw(unitcircle);
  ,#+END_SRC
  #+end_example

  #+cindex: @samp{file-desc}, header argument
  The =file-desc= header argument defines the description (see [[*Link
  Format]]) for the link.  If =file-desc= is present but has no value,
  the =file= value is used as the link description.  When this
  argument is not present, the description is omitted.  If you want to
  provide the =file-desc= argument but omit the description, you can
  provide it with an empty vector (i.e., :file-desc []).

  #+cindex: @samp{sep}, header argument
  By default, Org assumes that a table written to a file has
  TAB-delimited output.  You can choose a different separator with
  the =sep= header argument.

  #+cindex: @samp{file-mode}, header argument
  The =file-mode= header argument defines the file permissions.  To
  make it executable, use =:file-mode (identity #o755)=.

  #+begin_example
  ,#+BEGIN_SRC shell :results file :file script.sh :file-mode (identity #o755)
    echo "#!/bin/bash"
    echo "echo Hello World"
  ,#+END_SRC
  #+end_example

