#+chunk-id: org-manual-chunk-0061
#+source-file: org-manual
#+heading-path: Agenda Views > The Built-in Agenda Views > The global TODO list
#+start-line: 9294
#+end-line: 9369
#+external-urls: 
#+mirrored-urls: 
*** The global TODO list
:PROPERTIES:
:DESCRIPTION: All unfinished action items.
:ALT_TITLE: Global TODO list
:END:
#+cindex: global TODO list
#+cindex: TODO list, global

The global TODO list contains all unfinished TODO items formatted and
collected into a single place.

- {{{kbd(M-x org-agenda t)}}} (~org-todo-list~) ::

  #+kindex: t @r{(Agenda dispatcher)}
  #+findex: org-todo-list
  Show the global TODO list.  This collects the TODO items from all
  agenda files (see [[*Agenda Views]]) into a single buffer.  By default,
  this lists items with a state that is not a DONE state.  The buffer
  is in Agenda mode, so there are commands to examine and manipulate
  the TODO entries directly from that buffer (see [[*Commands in the
  Agenda Buffer]]).

- {{{kbd(M-x org-agenda T)}}} (~org-todo-list~) ::

  #+kindex: T @r{(Agenda dispatcher)}
  #+findex: org-todo-list
  #+cindex: TODO keyword matching
  #+vindex: org-todo-keywords
  Like the above, but allows selection of a specific TODO keyword.
  You can also do this by specifying a prefix argument to
  {{{kbd(t)}}}.  You are prompted for a keyword, and you may also
  specify several keywords by separating them with =|= as the boolean
  OR operator.  With a numeric prefix, the Nth keyword in
  ~org-todo-keywords~ is selected.

  #+kindex: r
  The {{{kbd(r)}}} key in the agenda buffer regenerates it, and you
  can give a prefix argument to this command to change the selected
  TODO keyword, for example {{{kbd(3 r)}}}.  If you often need
  a search for a specific keyword, define a custom command for it (see
  [[*The Agenda Dispatcher]]).

  Matching specific TODO keywords can also be done as part of a tags
  search (see [[*Tag Searches]]).

Remote editing of TODO items means that you can change the state of
a TODO entry with a single key press.  The commands available in the
TODO list are described in [[*Commands in the Agenda Buffer]].

#+cindex: sublevels, inclusion into TODO list
Normally the global TODO list simply shows all headlines with TODO
keywords.  This list can become very long.  There are two ways to keep
it more compact:

-
  #+vindex: org-agenda-todo-ignore-scheduled
  #+vindex: org-agenda-todo-ignore-deadlines
  #+vindex: org-agenda-todo-ignore-timestamp
  #+vindex: org-agenda-todo-ignore-with-date
  Some people view a TODO item that has been /scheduled/ for execution
  or have a /deadline/ (see [[*Timestamps]]) as no longer /open/.
  Configure the variables ~org-agenda-todo-ignore-scheduled~ to
  exclude some or all scheduled items from the global TODO list,
  ~org-agenda-todo-ignore-deadlines~ to exclude some or all items with
  a deadline set, ~org-agenda-todo-ignore-timestamp~ to exclude some
  or all items with an active timestamp other than a DEADLINE or
  a SCHEDULED timestamp and/or ~org-agenda-todo-ignore-with-date~ to
  exclude items with at least one active timestamp.

-
  #+vindex: org-agenda-todo-list-sublevels
  TODO items may have sublevels to break up the task into subtasks.
  In such cases it may be enough to list only the highest level TODO
  headline and omit the sublevels from the global list.  Configure the
  variable ~org-agenda-todo-list-sublevels~ to get this behavior.

