#+chunk-id: org-manual-chunk-0043
#+source-file: org-manual
#+heading-path: Dates and Times > Creating Timestamps > The date/time prompt
#+start-line: 6402
#+end-line: 6531
#+external-urls: 
#+mirrored-urls: 
*** The date/time prompt
:PROPERTIES:
:DESCRIPTION: How Org mode helps you enter dates and times.
:END:
#+cindex: date, reading in minibuffer
#+cindex: time, reading in minibuffer

#+vindex: org-read-date-prefer-future
When Org mode prompts for a date/time, the default is shown in default
date/time format, and the prompt therefore seems to ask for a specific
format.  But it in fact accepts date/time information in a variety of
formats.  Generally, the information should start at the beginning of
the string.  Org mode finds whatever information is in there and
derives anything you have not specified from the /default date and
time/.  The default is usually the current date and time, but when
modifying an existing timestamp, or when entering the second stamp of
a range, it is taken from the stamp in the buffer.  When filling in
information, Org mode assumes that most of the time you want to enter
a date in the future: if you omit the month/year and the given
day/month is /before/ today, it assumes that you mean a future
date[fn:21].  If the date has been automatically shifted into the
future, the time prompt shows this with =(=>F)=.

For example, let's assume that today is *June 13, 2006*.  Here is how
various inputs are interpreted, the items filled in by Org mode are in
*bold*.

| =3-2-5=        | \rArr{} 2003-02-05                              |
| =2/5/3=        | \rArr{} 2003-02-05                              |
| =14=           | \rArr{} *2006*-*06*-14                          |
| =12=           | \rArr{} *2006*-*07*-12                          |
| =2/5=          | \rArr{} *2007*-02-05                            |
| =Fri=          | \rArr{} nearest Friday (default date or later)  |
| =sep 15=       | \rArr{} *2006*-09-15                            |
| =feb 15=       | \rArr{} *2007*-02-15                            |
| =sep 12 9=     | \rArr{} 2009-09-12                              |
| =12:45=        | \rArr{} *2006*-*06*-*13* 12:45                  |
| =22 sept 0:34= | \rArr{} *2006*-09-22 0:34                       |
| =w4=           | \rArr{} ISO week for of the current year *2006* |
| =2012 w4 fri=  | \rArr{} Friday of ISO week 4 in 2012            |
| =2012-w04-5=   | \rArr{} Same as above                           |

Furthermore, you can specify a relative date by giving, as the /first/
thing in the input: a plus/minus sign, a number and a letter---=h=,
=d=, =w=, =m= or =y=---to indicate a change in hours, days, weeks,
months, or years.  With =h= the date is relative to the current time,
with the other letters and a single plus or minus, the date is
relative to today at 00:00.  With a double plus or minus, it is
relative to the default date.  If instead of a single letter, you use
the abbreviation of day name, the date is the Nth such day, e.g.:

| =+0=    | \rArr{} today                       |
| =.=     | \rArr{} today                       |
| =+2h=   | \rArr{} two hours from now          |
| =+4d=   | \rArr{} four days from today        |
| =+4=    | \rArr{} same as +4d                 |
| =+2w=   | \rArr{} two weeks from today        |
| =++5=   | \rArr{} five days from default date |
| =+2tue= | \rArr{} second Tuesday from now     |

#+vindex: parse-time-months
#+vindex: parse-time-weekdays
The function understands English month and weekday abbreviations.  If
you want to use unabbreviated names and/or other languages, configure
the variables ~parse-time-months~ and ~parse-time-weekdays~.

#+vindex: org-read-date-force-compatible-dates
Not all dates can be represented in a given Emacs implementation.  By
default, Org mode forces dates into the compatibility range 1970--2037
which works on all Emacs implementations.  If you want to use dates
outside this range, read the docstring of the variable
~org-read-date-force-compatible-dates~.

You can specify a time range by giving start and end times or by
giving a start time and a duration (in HH:MM format).  Use one or two
dash(es) as the separator in the former case and use =+= as the
separator in the latter case, e.g.:

| =11am-1:15pm=  | \rArr{} 11:00-13:15   |
| =11h-13h15=    | \rArr{} same as above |
| =11am--1:15pm= | \rArr{} same as above |
| =11am+2:15=    | \rArr{} same as above |

#+cindex: calendar, for selecting date
#+vindex: org-popup-calendar-for-date-prompt
Parallel to the minibuffer prompt, a calendar is popped up[fn:: If you
do not need/want the calendar, configure the variable
~org-popup-calendar-for-date-prompt~.].  When you exit the date
prompt, either by clicking on a date in the calendar, or by pressing
{{{kbd(RET)}}}, the date selected in the calendar is combined with the
information entered at the prompt.  You can control the calendar fully
from the minibuffer:

#+kindex: <
#+kindex: >
#+kindex: M-v
#+kindex: C-v
#+kindex: mouse-1
#+kindex: S-RIGHT
#+kindex: S-LEFT
#+kindex: S-DOWN
#+kindex: S-UP
#+kindex: M-S-RIGHT
#+kindex: M-S-LEFT
#+kindex: RET
#+kindex: .
#+kindex: C-.
#+attr_texinfo: :columns 0.25 0.55
| {{{kbd(RET)}}}       | Choose date at point in calendar.      |
| {{{kbd(mouse-1)}}}   | Select date by clicking on it.         |
| {{{kbd(S-RIGHT)}}}   | One day forward.                       |
| {{{kbd(S-LEFT)}}}    | One day backward.                      |
| {{{kbd(S-DOWN)}}}    | One week forward.                      |
| {{{kbd(S-UP)}}}      | One week backward.                     |
| {{{kbd(M-S-RIGHT)}}} | One month forward.                     |
| {{{kbd(M-S-LEFT)}}}  | One month backward.                    |
| {{{kbd(>)}}}         | Scroll calendar forward by one month.  |
| {{{kbd(<)}}}         | Scroll calendar backward by one month. |
| {{{kbd(M-v)}}}       | Scroll calendar forward by 3 months.   |
| {{{kbd(C-v)}}}       | Scroll calendar backward by 3 months.  |
| {{{kbd(C-.)}}}       | Select today's date[fn:22]             |

#+vindex: org-read-date-display-live
The actions of the date/time prompt may seem complex, but I assure you
they will grow on you, and you will start getting annoyed by pretty
much any other way of entering a date/time out there.  To help you
understand what is going on, the current interpretation of your input
is displayed live in the minibuffer[fn:: If you find this distracting,
turn off the display with ~org-read-date-display-live~.].

