#+chunk-id: org-manual-chunk-0055
#+source-file: org-manual
#+heading-path: Capture and Attachments > Attachments > Attachment defaults and dispatcher
#+start-line: 8519
#+end-line: 8641
#+external-urls: 
#+mirrored-urls: 
*** Attachment defaults and dispatcher
:PROPERTIES:
:DESCRIPTION: How to access attachment commands
:END:

By default, Org attach uses =ID= properties when adding attachments to
headings.  This makes working with attachments fully automated.  There
is no decision needed for folder-name or location.  =ID=-based
directories are by default located in the =data/= directory, which
lives in the same directory where your Org file lives[fn:: If you move
entries or Org files from one directory to another, you may want to
configure ~org-attach-id-dir~ to contain an absolute path.].

When attachments are made using ~org-attach~ a default tag =ATTACH= is
added to the node that gets the attachments.

For more control over the setup, see [[*Attachment options]].

The following commands deal with attachments:

- {{{kbd(C-c C-a)}}} (~org-attach~) ::

  #+kindex: C-c C-a
  #+findex: org-attach
  The dispatcher for commands related to the attachment system.  After
  these keys, a list of commands is displayed, and you must press an
  additional key to select a command:

  - {{{kbd(a)}}} (~org-attach-attach~) ::

    #+kindex: C-c C-a a
    #+findex: org-attach-attach
    #+vindex: org-attach-method
    Select a file and move it into the task's attachment directory.
    The file is copied, moved, or linked, depending on
    ~org-attach-method~.  Note that hard links are not supported on
    all systems.

  - {{{kbd(c)}}}/{{{kbd(m)}}}/{{{kbd(l)}}} ::

    #+kindex: C-c C-a c
    #+kindex: C-c C-a m
    #+kindex: C-c C-a l
    Attach a file using the copy/move/link method.  Note that hard
    links are not supported on all systems.

  - {{{kbd(b)}}} (~org-attach-buffer~) ::

    #+kindex: C-c C-a b
    #+findex: org-attach-buffer
    Select a buffer and save it as a file in the task's attachment
    directory.

  - {{{kbd(n)}}} (~org-attach-new~) ::

    #+kindex: C-c C-a n
    #+findex: org-attach-new
    Create a new attachment as an Emacs buffer.

  - {{{kbd(z)}}} (~org-attach-sync~) ::

    #+kindex: C-c C-a z
    #+findex: org-attach-sync
    Synchronize the current task with its attachment directory, in
    case you added attachments yourself.

  - {{{kbd(o)}}} (~org-attach-open~) ::

    #+kindex: C-c C-a o
    #+findex: org-attach-open
    #+vindex: org-file-apps
    Open current task's attachment.  If there is more than one, prompt
    for a file name first.  Opening follows the rules set by
    ~org-file-apps~.  For more details, see the information on
    following hyperlinks (see [[*Handling Links]]).

  - {{{kbd(O)}}} (~org-attach-open-in-emacs~) ::

    #+kindex: C-c C-a O
    #+findex: org-attach-open-in-emacs
    Also open the attachment, but force opening the file in Emacs.

  - {{{kbd(f)}}} (~org-attach-reveal~) ::

    #+kindex: C-c C-a f
    #+findex: org-attach-reveal
    Open the current task's attachment directory.

  - {{{kbd(F)}}} (~org-attach-reveal-in-emacs~) ::

    #+kindex: C-c C-a F
    #+findex: org-attach-reveal-in-emacs
    Also open the directory, but force using Dired in Emacs.

  - {{{kbd(d)}}} (~org-attach-delete-one~) ::

    #+kindex: C-c C-a d
    Select and delete a single attachment.

  - {{{kbd(D)}}} (~org-attach-delete-all~) ::

    #+kindex: C-c C-a D
    Delete all of a task's attachments.  A safer way is to open the
    directory in Dired and delete from there.

  - {{{kbd(s)}}} (~org-attach-set-directory~) ::

    #+kindex: C-c C-a s
    #+cindex: @samp{DIR}, property
    Set a specific directory as the entry's attachment directory.
    This works by putting the directory path into the =DIR=
    property.

  - {{{kbd(S)}}} (~org-attach-unset-directory~) ::

    #+kindex: C-c C-a S
    #+cindex: @samp{DIR}, property
    Remove the attachment directory.  This command removes the =DIR=
    property and asks the user to either move content inside that
    folder, if an =ID= property is set, delete the content, or to
    leave the attachment directory as is but no longer attached to the
    heading.

