#+chunk-id: org-manual-chunk-0157
#+source-file: org-manual
#+heading-path: Exporting > Advanced Export Configuration > Extending an existing backend
#+start-line: 17059
#+end-line: 17118
#+external-urls: https://orgmode.org/worg/dev/org-export-reference.html
#+mirrored-urls: https://orgmode.org/worg/dev/org-export-reference.html
*** Extending an existing backend
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Some parts of the conversion process can be extended for certain
elements to introduce a new or revised translation.  That is how
the HTML export backend was extended to handle Markdown format.  The
extensions work seamlessly so any aspect of filtering not done by the
extended backend is handled by the original backend.  Of all the
export customization in Org, extending is very powerful as it operates
at the parser level.

For this example, make the /ascii/ backend display the language used
in a source code block.  Also make it display only when some attribute
is non-~nil~, like the following:

: #+ATTR_ASCII: :language t

Then extend ASCII backend with a custom "my-ascii" backend.

#+begin_src emacs-lisp
(defun my-ascii-src-block (src-block contents info)
  "Transcode a SRC-BLOCK element from Org to ASCII.
CONTENTS is nil.  INFO is a plist used as a communication
channel."
  (if (not (org-export-read-attribute :attr_ascii src-block :language))
      (org-export-with-backend 'ascii src-block contents info)
    (concat
     (format ",--[ %s ]--\n%s`----"
             (org-element-property :language src-block)
             (replace-regexp-in-string
              "^" "| "
              (org-element-normalize-string
               (org-export-format-code-default src-block info)))))))

(org-export-define-derived-backend 'my-ascii 'ascii
  :translate-alist '((src-block . my-ascii-src-block)))
#+end_src

The ~my-ascii-src-block~ function looks at the attribute above the
current element.  If not true, hands over to /ascii/ backend.  If
true, which it is in this example, it creates a box around the code
and leaves room for the inserting a string for language.  The last
form creates the new backend that springs to action only when
translating ~src-block~ type elements.

To use the newly defined backend, evaluate the following from an Org
buffer:

#+begin_src emacs-lisp
(org-export-to-buffer 'my-ascii "*Org MY-ASCII Export*")
#+end_src

Further steps to consider would be an interactive function,
self-installing an item in the export dispatcher menu, and other
user-friendly improvements.  See
<../../mirror/by-url/b22be4dccd11ae6f7401a8c7ddc613c1e2612639073384072249e8dcd860fa45.html> for more
details.

