#+chunk-id: org-manual-chunk-0131
#+source-file: org-manual
#+heading-path: Exporting > OpenDocument Text Export > Tables in ODT export
#+start-line: 15284
#+end-line: 15331
#+external-urls: 
#+mirrored-urls: 
*** Tables in ODT export
:PROPERTIES:
:DESCRIPTION: Org tables conversions.
:END:

#+cindex: tables, in ODT export

The ODT export backend handles native Org mode tables (see [[*Tables]])
and simple =table.el= tables.  Complex =table.el= tables having column
or row spans are not supported.  Such tables are stripped from the
exported document.

By default, the ODT export backend exports a table with top and
bottom frames and with ruled lines separating row and column groups
(see [[*Column Groups]]).  All tables are typeset to occupy the same
width.  The ODT export backend honors any table alignments and
relative widths for columns (see [[*Column Width and Alignment]]).

Note that the ODT export backend interprets column widths as weighted
ratios, the default weight being 1.

#+cindex: @samp{ATTR_ODT}, keyword
Specifying =:rel-width= property on an =ATTR_ODT= line controls the
width of the table.  For example:

#+begin_example
,#+ATTR_ODT: :rel-width 50
| Area/Month    |   Jan |   Feb |   Mar |   Sum |
|---------------+-------+-------+-------+-------|
| /             |     < |       |       |     < |
| <l13>         |  <r5> |  <r5> |  <r5> |  <r6> |
| North America |     1 |    21 |   926 |   948 |
| Middle East   |     6 |    75 |   844 |   925 |
| Asia Pacific  |     9 |    27 |   790 |   826 |
|---------------+-------+-------+-------+-------|
| Sum           |    16 |   123 |  2560 |  2699 |
#+end_example

On export, the above table takes 50% of text width area.  The exporter
sizes the columns in the ratio: 13:5:5:5:6.  The first column is
left-aligned and rest of the columns, right-aligned.  Vertical rules
separate the header and the last column.  Horizontal rules separate
the header and the last row.

For even more customization, create custom table styles and associate
them with a table using the =ATTR_ODT= keyword.  See [[*Customizing
tables in ODT export]].

