#+chunk-id: org-manual-chunk-0051
#+source-file: org-manual
#+heading-path: Refiling and Archiving > Archiving > Internal archiving
#+start-line: 7789
#+end-line: 7868
#+external-urls: 
#+mirrored-urls: 
*** Internal archiving
:PROPERTIES:
:DESCRIPTION: Switch off a tree but keep it in the file.
:END:

#+cindex: @samp{ARCHIVE}, tag
If you want to just switch off---for agenda views---certain subtrees
without moving them to a different file, you can use the =ARCHIVE=
tag.

A headline that is marked with the =ARCHIVE= tag (see [[*Tags]]) stays at
its location in the outline tree, but behaves in the following way:

-
  #+vindex: org-cycle-open-archived-trees
  It does not open when you attempt to do so with a visibility cycling
  command (see [[*Visibility Cycling]]).  You can force cycling archived
  subtrees with {{{kbd(C-c C-TAB)}}}, or by setting the option
  ~org-cycle-open-archived-trees~.  Also, normal outline commands, like
  ~org-fold-show-all~, open archived subtrees.

-
  #+vindex: org-sparse-tree-open-archived-trees
  During sparse tree construction (see [[*Sparse Trees]]), matches in
  archived subtrees are not exposed, unless you configure the option
  ~org-sparse-tree-open-archived-trees~.

-
  #+vindex: org-agenda-skip-archived-trees
  During agenda view construction (see [[*Agenda Views]]), the content of
  archived trees is ignored unless you configure the option
  ~org-agenda-skip-archived-trees~, in which case these trees are
  always included.  In the agenda you can press {{{kbd(v a)}}} to get
  archives temporarily included.

-
  #+vindex: org-export-with-archived-trees
  Archived trees are not exported (see [[*Exporting]]), only the headline
  is.  Configure the details using the variable
  ~org-export-with-archived-trees~.

-
  #+vindex: org-columns-skip-archived-trees
  Archived trees are excluded from column view unless the variable
  ~org-columns-skip-archived-trees~ is configured to ~nil~.

The following commands help manage the =ARCHIVE= tag:

- {{{kbd(C-c C-x a)}}} (~org-toggle-archive-tag~) ::

  #+kindex: C-c C-x a
  #+findex: org-toggle-archive-tag
  Toggle the archive tag for the current headline.  When the tag is
  set, the headline changes to a shadowed face, and the subtree below
  it is hidden.

- {{{kbd(C-u C-c C-x a)}}} ::

  #+kindex: C-u C-c C-x a
  Check if any direct children of the current headline should be
  archived.  To do this, check each subtree for open TODO entries.  If
  none is found, the command offers to set the =ARCHIVE= tag for the
  child.  If point is /not/ on a headline when this command is
  invoked, check the level 1 trees.

- {{{kbd(C-c C-TAB)}}} (~org-cycle-force-archived~) ::

  #+kindex: C-c C-TAB
  Cycle a tree even if it is tagged with =ARCHIVE=.

- {{{kbd(C-c C-x A)}}} (~org-archive-to-archive-sibling~) ::

  #+kindex: C-c C-x A
  #+findex: org-archive-to-archive-sibling
  Move the current entry to the /Archive Sibling/.  This is a sibling
  of the entry with the heading =Archive= and the archive tag.  The
  entry becomes a child of that sibling and in this way retains a lot
  of its original context, including inherited tags and approximate
  position in the outline.

