#+chunk-id: org-manual-chunk-0097
#+source-file: org-manual
#+heading-path: Exporting > HTML Export > HTML doctypes
#+start-line: 13514
#+end-line: 13599
#+external-urls: 
#+mirrored-urls: 
*** HTML doctypes
:PROPERTIES:
:DESCRIPTION: Exporting various (X)HTML flavors.
:END:

Org can export to various (X)HTML flavors.

#+vindex: org-html-doctype
#+vindex: org-html-doctype-alist
Set the ~org-html-doctype~ variable for different (X)HTML variants.
Depending on the variant, the HTML exporter adjusts the syntax of HTML
conversion accordingly.  Org includes the following ready-made
variants:

- ~"html4-strict"~
- ~"html4-transitional"~
- ~"html4-frameset"~
- ~"xhtml-strict"~
- ~"xhtml-transitional"~
- ~"xhtml-frameset"~
- ~"xhtml-11"~
- ~"html5"~
- ~"xhtml5"~

#+texinfo: @noindent
See the variable ~org-html-doctype-alist~ for details.  The default is
~"xhtml-strict"~.

#+vindex: org-html-html5-fancy
#+cindex: @samp{HTML5}, export new elements
Org's HTML exporter does not by default enable new block elements
introduced with the HTML5 standard.  To enable them, set
~org-html-html5-fancy~ to non-~nil~.  Or use an =OPTIONS= line in the
file to set =html5-fancy=.

HTML5 documents can have arbitrary =#+BEGIN= ... =#+END= blocks.
For example:

#+begin_example
,#+BEGIN_aside
  Lorem ipsum
,#+END_aside
#+end_example

#+texinfo: @noindent
exports to:

#+begin_src html
<aside>
  <p>Lorem ipsum</p>
</aside>
#+end_src

#+texinfo: @noindent
while this:

#+begin_example
,#+ATTR_HTML: :controls controls :width 350
,#+BEGIN_video
,#+HTML: <source src="movie.mp4" type="video/mp4">
,#+HTML: <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
,#+END_video
#+end_example

#+texinfo: @noindent
exports to:

#+begin_src html
<video controls="controls" width="350">
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  <p>Your browser does not support the video tag.</p>
</video>
#+end_src

#+vindex: org-html-html5-elements
When special blocks do not have a corresponding HTML5 element, the
HTML exporter reverts to standard translation (see
~org-html-html5-elements~).  For example, =#+BEGIN_lederhosen= exports
to ~<div class="lederhosen">~.

Special blocks cannot have headlines.  For the HTML exporter to wrap
the headline and its contents in ~<section>~ or ~<article>~ tags, set
the =HTML_CONTAINER= property for the headline.

