#+chunk-id: org-manual-chunk-0190
#+source-file: org-manual
#+heading-path: Miscellaneous > A Cleaner Outline View > Hard indentation
#+start-line: 20583
#+end-line: 20633
#+external-urls: 
#+mirrored-urls: 
*** Hard indentation

It is possible to use hard spaces to achieve the indentation instead,
if the bare ASCII file should have the indented look also outside
Emacs[fn:52].  With Org's support, you have to indent all lines to
line up with the outline headers.  You would use these settings[fn::
~org-adapt-indentation~ can also be set to ='headline-data=, in which
case only data lines below the headline will be indented.]:

#+begin_src emacs-lisp
(setq org-adapt-indentation t
      org-hide-leading-stars t
      org-odd-levels-only t)
#+end_src

- /Indentation of text below headlines/ (~org-adapt-indentation~) ::

  #+vindex: org-adapt-indentation
  The first setting modifies paragraph filling, line wrapping, and
  structure editing commands to preserving or adapting the indentation
  as appropriate.

- /Hiding leading stars/ (~org-hide-leading-stars~) ::

  #+vindex: org-hide-leading-stars
  #+vindex: org-hide, face
  The second setting makes leading stars invisible by applying the
  face ~org-hide~ to them.  For per-file preference, use these file
  =STARTUP= options:

  #+begin_example
  ,#+STARTUP: hidestars
  ,#+STARTUP: showstars
  #+end_example

- /Odd levels/ (~org-odd-levels-only~) ::

  #+vindex: org-odd-levels-only
  The third setting makes Org use only odd levels, 1, 3, 5, ..., in
  the outline to create more indentation.  On a per-file level,
  control this with:

  #+begin_example
  ,#+STARTUP: odd
  ,#+STARTUP: oddeven
  #+end_example

  To convert a file between single and double stars layouts, use
  {{{kbd(M-x org-convert-to-odd-levels)}}} and {{{kbd(M-x
  org-convert-to-oddeven-levels)}}}.

