#+chunk-id: org-manual-chunk-0080
#+source-file: org-manual
#+heading-path: Markup for Rich Contents > Embedded LaTeX > Previewing LaTeX fragments
#+start-line: 11588
#+end-line: 11630
#+external-urls: 
#+mirrored-urls: 
*** Previewing LaTeX fragments
:PROPERTIES:
:DESCRIPTION: What will this snippet look like?
:END:
#+cindex: @LaTeX{} fragments, preview

#+vindex: org-preview-latex-default-process
If you have a working LaTeX installation and =dvipng=, =dvisvgm= or
=convert= installed[fn:39], LaTeX fragments can be processed to
produce images of the typeset expressions to be used for inclusion
while exporting to HTML (see [[*LaTeX fragments]]), or for inline
previewing within Org mode.

#+vindex: org-format-latex-options
#+vindex: org-format-latex-header
You can customize the variables ~org-format-latex-options~ and
~org-format-latex-header~ to influence some aspects of the preview.
In particular, the ~:scale~ (and for HTML export, ~:html-scale~)
property of the former can be used to adjust the size of the preview
images.

- {{{kbd(C-c C-x C-l)}}} (~org-latex-preview~) ::
  #+kindex: C-c C-x C-l
  #+findex: org-latex-preview

  Produce a preview image of the LaTeX fragment at point and overlay
  it over the source code.  If there is no fragment at point, process
  all fragments in the current entry---between two headlines.

  When called with a single prefix argument, clear all images in the
  current entry.  Two prefix arguments produce a preview image for all
  fragments in the buffer, while three of them clear all the images in
  that buffer.

#+vindex: org-startup-with-latex-preview
You can turn on the previewing of all LaTeX fragments in a file with

: #+STARTUP: latexpreview

To disable it, simply use

: #+STARTUP: nolatexpreview

