#+chunk-id: org-manual-chunk-0053
#+source-file: org-manual
#+heading-path: Capture and Attachments > Capture > Using capture
#+start-line: 7912
#+end-line: 7979
#+external-urls: 
#+mirrored-urls: 
*** Using capture
:PROPERTIES:
:DESCRIPTION: Commands to invoke and terminate capture.
:END:

- {{{kbd(M-x org-capture)}}} (~org-capture~) ::

  #+findex: org-capture
  Display the capture templates menu.  If you have templates defined
  (see [[*Capture templates]]), it offers these templates for
  selection.  It inserts the template into the target file and
  switches to an indirect buffer narrowed to this new node.  You may
  then insert the information you want.

- {{{kbd(C-c C-c)}}} (~org-capture-finalize~) ::

  #+kindex: C-c C-c @r{(Capture buffer)}
  #+findex: org-capture-finalize
  Once you have finished entering information into the capture buffer,
  {{{kbd(C-c C-c)}}} returns you to the window configuration before
  the capture process, so that you can resume your work without
  further distraction.  When called with a prefix argument, finalize
  and then jump to the captured item.

- {{{kbd(C-c C-w)}}} (~org-capture-refile~) ::

  #+kindex: C-c C-w @r{(Capture buffer)}
  #+findex: org-capture-refile
  Finalize the capture process by refiling the note to a different
  place (see [[*Refile and Copy]]).  Please realize that this is a normal
  refiling command that will be executed---so point position at the
  moment you run this command is important.  If you have inserted
  a tree with a parent and children, first move point back to the
  parent.  Any prefix argument given to this command is passed on to
  the ~org-refile~ command.

- {{{kbd(C-c C-k)}}} (~org-capture-kill~) ::

  #+kindex: C-c C-k @r{(Capture buffer)}
  #+findex: org-capture-kill
  Abort the capture process and return to the previous state.

#+kindex: k c @r{(Agenda)}
You can also call ~org-capture~ in a special way from the agenda,
using the {{{kbd(k c)}}} key combination.  With this access, any
timestamps inserted by the selected capture template defaults to the
date at point in the agenda, rather than to the current date.

To find the locations of the last stored capture, use ~org-capture~
with prefix commands:

- {{{kbd(C-u M-x org-capture)}}} ::

  Visit the target location of a capture template.  You get to select
  the template in the usual way.

- {{{kbd(C-u C-u M-x org-capture)}}} ::

  Visit the last stored capture item in its buffer.

#+vindex: org-bookmark-names-plist
#+vindex: org-capture-last-stored
You can also jump to the bookmark ~org-capture-last-stored~, which is
automatically created unless you customize ~org-bookmark-names-plist~.

To insert the capture at point in an Org buffer, call ~org-capture~
with a {{{kbd(C-0)}}} prefix argument.

