#+chunk-id: org-manual-chunk-0006
#+source-file: org-manual
#+heading-path: Introduction > Feedback > How to profile Org performance
#+start-line: 371
#+end-line: 431
#+external-urls: 
#+mirrored-urls: 
*** How to profile Org performance
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+cindex: profiler
Sometimes, Org becomes slow for no apparent reason.  Such slowdown
is often caused by interaction between third-party packages and Org
mode.  However, identifying the root cause is not always straightforward.

Emacs is able to record performance statistics, which can then be used
to find out which functions are taking the most time to execute.  To
record the statistics, one can use a profiler.  To use the Emacs
profiler, we recommend the following steps:

1. Make sure that no profiler is currently active:

   : M-x profiler-stop <RET>

2. Start a new CPU profiler session:

   : M-x profiler-start <RET> cpu <RET>

3. Use Emacs as usual, performing the actions that are deemed slow.

4. Display and examine the recorded performance statistics:

   : M-x profiler-report <RET>

   This command will display a summary of the commands and functions
   that have been executed between ~profiler-start~ and
   ~profiler-report~ invocations, with the command taking the most
   time displayed on top.

   The =<TAB>= key can be used to fold and unfold lines in the profiler
   buffer.  The child items revealed upon unfolding are the functions
   and commands called by the unfolded parent.

   The root causes are often buried deep inside child items in
   the profiler.  You can press =B= (~profiler-report-render-reversed-calltree~)
   to quickly reveal the actual function/command that takes the most
   time to run.

   Pressing =C= ~profiler-report-render-calltree~ will recover the
   original view.

5. If you need further help, you can share the statistics data.

   To save the data, issue

   : M-x profiler-report-write-profile <RET>
   : /path/to/profile-file-to-be-saved <RET>

   Then, you can attach the saved file to your email to the Org
   mailing list, along with details about what you did to trigger the
   slowdown.

   Note that the saved statistics will only contain the function names
   and how long their execution takes.  No private data will be
   recorded.

