#+chunk-id: org-manual-chunk-0141
#+source-file: org-manual
#+heading-path: Exporting > Texinfo Export > Texinfo title and copyright page
#+start-line: 16100
#+end-line: 16140
#+external-urls: 
#+mirrored-urls: 
*** Texinfo title and copyright page
:PROPERTIES:
:DESCRIPTION: Creating preamble pages.
:END:

#+cindex: @samp{TEXINFO_PRINTED_TITLE}, keyword
The default template for hard copy output has a title page with
=TITLE= and =AUTHOR= keywords (see [[*Export Settings]]).  To replace the
regular title with something different for the printed version, use
the =TEXINFO_PRINTED_TITLE= and =SUBTITLE= keywords.  Both expect raw
Texinfo code for setting their values.

#+cindex: @samp{SUBAUTHOR}, keyword
If one =AUTHOR= line is not sufficient, add multiple =SUBAUTHOR=
keywords.  They have to be set in raw Texinfo code.

#+begin_example
,#+AUTHOR: Jane Smith
,#+SUBAUTHOR: John Doe
,#+TEXINFO_PRINTED_TITLE: This Long Title@@inlinefmt{tex,@*} Is Broken in @TeX{}
#+end_example

#+cindex: @samp{COPYING}, property
Copying material is defined in a dedicated headline with a non-~nil~
=COPYING= property.  The backend inserts the contents within
a =@copying= command at the beginning of the document.  The heading
itself does not appear in the structure of the document.

Copyright information is printed on the back of the title page.

#+begin_example
,* Legalese
  :PROPERTIES:
  :COPYING: t
  :END:

  This is a short example of a complete Texinfo file, version 1.0.

  Copyright \copy 2016 Free Software Foundation, Inc.
#+end_example

