#+chunk-id: org-manual-chunk-0064
#+source-file: org-manual
#+heading-path: Agenda Views > The Built-in Agenda Views > Stuck projects
#+start-line: 9618
#+end-line: 9670
#+external-urls: 
#+mirrored-urls: 
*** Stuck projects
:PROPERTIES:
:DESCRIPTION: Find projects you need to review.
:END:
#+pindex: GTD, Getting Things Done

If you are following a system like David Allen's GTD to organize your
work, one of the "duties" you have is a regular review to make sure
that all projects move along.  A /stuck/ project is a project that has
no defined next actions, so it never shows up in the TODO lists Org
mode produces.  During the review, you need to identify such projects
and define next actions for them.

- {{{kbd(M-x org-agenda #)}}} (~org-agenda-list-stuck-projects~) ::

  #+kindex: # @r{(Agenda dispatcher)}
  #+findex: org-agenda-list-stuck-projects
  List projects that are stuck.

- {{{kbd(M-x org-agenda !)}}} ::

  #+kindex: ! @r{(Agenda dispatcher)}
  #+vindex: org-stuck-projects
  Customize the variable ~org-stuck-projects~ to define what a stuck
  project is and how to find it.

You almost certainly need to configure this view before it works for
you.  The built-in default assumes that all your projects are level-2
headlines, and that a project is not stuck if it has at least one
entry marked with a TODO keyword =TODO= or =NEXT= or =NEXTACTION=.

Let's assume that you, in your own way of using Org mode, identify
projects with a tag =:PROJECT:=, and that you use a TODO keyword
=MAYBE= to indicate a project that should not be considered yet.
Let's further assume that the TODO keyword =DONE= marks finished
projects, and that =NEXT= and =TODO= indicate next actions.  The tag
=:@shop:= indicates shopping and is a next action even without the
NEXT tag.  Finally, if the project contains the special word =IGNORE=
anywhere, it should not be listed either.  In this case you would
start by identifying eligible projects with a tags/TODO match (see
[[*Tag Searches]]) =+PROJECT/-MAYBE-DONE=, and then check for =TODO=,
=NEXT=, =@shop=, and =IGNORE= in the subtree to identify projects that
are not stuck.  The correct customization for this is:

#+begin_src emacs-lisp
(setq org-stuck-projects
      '("+PROJECT/-MAYBE-DONE" ("NEXT" "TODO") ("@shop")
        "\\<IGNORE\\>"))
#+end_src

Note that if a project is identified as non-stuck, the subtree of this
entry is searched for stuck projects.

